-- frequencia_dosagem: (1/day, 1/week, 2/day, 2/week, 3/day, 3/week, 4/week, 5/week,
-- "1 after waking up, 1 before going to sleep", 1 before bed, 1 in the morning, 
-- "1 after any meal", "2 after any meals (Different meals)")

-- insert 1000 rows

INSERT INTO ClienteMedicamento VALUES (144,35,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (733,31,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (935,36,'1/day');
INSERT INTO ClienteMedicamento VALUES (247,10,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (355,10,'3/day');
INSERT INTO ClienteMedicamento VALUES (892,10,'5/week');
INSERT INTO ClienteMedicamento VALUES (910,17,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (83,9,'2/day');
INSERT INTO ClienteMedicamento VALUES (426,16,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (111,19,'1/day');
INSERT INTO ClienteMedicamento VALUES (770,36,'5/week');
INSERT INTO ClienteMedicamento VALUES (66,26,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (384,10,'2/week');
INSERT INTO ClienteMedicamento VALUES (721,4,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (766,22,'3/week');
INSERT INTO ClienteMedicamento VALUES (136,37,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (699,4,'1/day');
INSERT INTO ClienteMedicamento VALUES (376,32,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (258,9,'1/week');
INSERT INTO ClienteMedicamento VALUES (254,12,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (836,36,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (261,32,'5/week');
INSERT INTO ClienteMedicamento VALUES (534,30,'2/day');
INSERT INTO ClienteMedicamento VALUES (906,18,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (881,18,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (931,11,'1/week');
INSERT INTO ClienteMedicamento VALUES (34,11,'1/day');
INSERT INTO ClienteMedicamento VALUES (577,19,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (102,36,'1/week');
INSERT INTO ClienteMedicamento VALUES (754,2,'5/week');
INSERT INTO ClienteMedicamento VALUES (793,14,'2/week');
INSERT INTO ClienteMedicamento VALUES (76,23,'2/week');
INSERT INTO ClienteMedicamento VALUES (708,26,'3/week');
INSERT INTO ClienteMedicamento VALUES (608,28,'1/week');
INSERT INTO ClienteMedicamento VALUES (68,23,'3/day');
INSERT INTO ClienteMedicamento VALUES (433,29,'5/week');
INSERT INTO ClienteMedicamento VALUES (704,38,'3/week');
INSERT INTO ClienteMedicamento VALUES (290,21,'2/week');
INSERT INTO ClienteMedicamento VALUES (310,22,'1/week');
INSERT INTO ClienteMedicamento VALUES (213,2,'3/day');
INSERT INTO ClienteMedicamento VALUES (738,38,'1/day');
INSERT INTO ClienteMedicamento VALUES (389,25,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (947,40,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (304,25,'4/week');
INSERT INTO ClienteMedicamento VALUES (933,7,'5/week');
INSERT INTO ClienteMedicamento VALUES (939,25,'3/week');
INSERT INTO ClienteMedicamento VALUES (448,8,'3/day');
INSERT INTO ClienteMedicamento VALUES (276,38,'3/day');
INSERT INTO ClienteMedicamento VALUES (182,6,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (497,39,'1/day');
INSERT INTO ClienteMedicamento VALUES (257,31,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (301,19,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (739,3,'3/day');
INSERT INTO ClienteMedicamento VALUES (197,21,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (140,1,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (831,31,'5/week');
INSERT INTO ClienteMedicamento VALUES (382,24,'5/week');
INSERT INTO ClienteMedicamento VALUES (203,10,'3/day');
INSERT INTO ClienteMedicamento VALUES (611,36,'2/day');
INSERT INTO ClienteMedicamento VALUES (337,25,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (747,30,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (96,8,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (873,18,'2/week');
INSERT INTO ClienteMedicamento VALUES (244,32,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (719,2,'3/day');
INSERT INTO ClienteMedicamento VALUES (576,32,'1/day');
INSERT INTO ClienteMedicamento VALUES (236,15,'3/day');
INSERT INTO ClienteMedicamento VALUES (161,18,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (388,12,'3/day');
INSERT INTO ClienteMedicamento VALUES (124,11,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (650,13,'3/week');
INSERT INTO ClienteMedicamento VALUES (57,28,'1/day');
INSERT INTO ClienteMedicamento VALUES (912,15,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (529,27,'4/week');
INSERT INTO ClienteMedicamento VALUES (66,29,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (735,30,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (246,19,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (702,33,'3/week');
INSERT INTO ClienteMedicamento VALUES (699,36,'1/week');
INSERT INTO ClienteMedicamento VALUES (411,34,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (611,1,'1/day');
INSERT INTO ClienteMedicamento VALUES (374,4,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (834,22,'3/day');
INSERT INTO ClienteMedicamento VALUES (423,34,'2/day');
INSERT INTO ClienteMedicamento VALUES (941,33,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (468,1,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (470,6,'4/week');
INSERT INTO ClienteMedicamento VALUES (682,21,'1/day');
INSERT INTO ClienteMedicamento VALUES (815,20,'1/day');
INSERT INTO ClienteMedicamento VALUES (171,2,'3/week');
INSERT INTO ClienteMedicamento VALUES (481,10,'3/day');
INSERT INTO ClienteMedicamento VALUES (277,38,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (700,31,'2/week');
INSERT INTO ClienteMedicamento VALUES (568,7,'4/week');
INSERT INTO ClienteMedicamento VALUES (23,14,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (70,5,'4/week');
INSERT INTO ClienteMedicamento VALUES (313,24,'5/week');
INSERT INTO ClienteMedicamento VALUES (488,8,'1/day');
INSERT INTO ClienteMedicamento VALUES (128,19,'1/day');
INSERT INTO ClienteMedicamento VALUES (484,17,'1/day');
INSERT INTO ClienteMedicamento VALUES (674,29,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (108,19,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (599,12,'3/week');
INSERT INTO ClienteMedicamento VALUES (193,30,'2/week');
INSERT INTO ClienteMedicamento VALUES (417,3,'5/week');
INSERT INTO ClienteMedicamento VALUES (688,37,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (977,2,'2/day');
INSERT INTO ClienteMedicamento VALUES (847,40,'3/week');
INSERT INTO ClienteMedicamento VALUES (828,36,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (131,17,'3/day');
INSERT INTO ClienteMedicamento VALUES (47,4,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (225,28,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (776,34,'3/week');
INSERT INTO ClienteMedicamento VALUES (792,5,'1/week');
INSERT INTO ClienteMedicamento VALUES (462,3,'3/week');
INSERT INTO ClienteMedicamento VALUES (856,24,'3/week');
INSERT INTO ClienteMedicamento VALUES (386,40,'1/day');
INSERT INTO ClienteMedicamento VALUES (553,9,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (636,8,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (89,31,'1/week');
INSERT INTO ClienteMedicamento VALUES (750,35,'1/week');
INSERT INTO ClienteMedicamento VALUES (732,18,'2/week');
INSERT INTO ClienteMedicamento VALUES (699,8,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (278,4,'4/week');
INSERT INTO ClienteMedicamento VALUES (447,9,'5/week');
INSERT INTO ClienteMedicamento VALUES (868,18,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (870,3,'4/week');
INSERT INTO ClienteMedicamento VALUES (395,15,'4/week');
INSERT INTO ClienteMedicamento VALUES (298,3,'2/week');
INSERT INTO ClienteMedicamento VALUES (291,18,'5/week');
INSERT INTO ClienteMedicamento VALUES (258,23,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (458,33,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (421,13,'1/day');
INSERT INTO ClienteMedicamento VALUES (139,34,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (85,1,'2/day');
INSERT INTO ClienteMedicamento VALUES (686,35,'5/week');
INSERT INTO ClienteMedicamento VALUES (567,10,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (397,1,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (223,2,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (21,25,'2/week');
INSERT INTO ClienteMedicamento VALUES (581,17,'1/week');
INSERT INTO ClienteMedicamento VALUES (750,22,'2/day');
INSERT INTO ClienteMedicamento VALUES (178,20,'3/day');
INSERT INTO ClienteMedicamento VALUES (505,33,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (35,22,'1/day');
INSERT INTO ClienteMedicamento VALUES (579,4,'2/week');
INSERT INTO ClienteMedicamento VALUES (111,32,'5/week');
INSERT INTO ClienteMedicamento VALUES (99,37,'2/day');
INSERT INTO ClienteMedicamento VALUES (361,22,'2/week');
INSERT INTO ClienteMedicamento VALUES (710,29,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (748,31,'5/week');
INSERT INTO ClienteMedicamento VALUES (849,28,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (616,28,'2/week');
INSERT INTO ClienteMedicamento VALUES (946,19,'1/day');
INSERT INTO ClienteMedicamento VALUES (95,8,'4/week');
INSERT INTO ClienteMedicamento VALUES (78,37,'1/day');
INSERT INTO ClienteMedicamento VALUES (528,13,'1/week');
INSERT INTO ClienteMedicamento VALUES (166,37,'4/week');
INSERT INTO ClienteMedicamento VALUES (775,26,'2/week');
INSERT INTO ClienteMedicamento VALUES (782,38,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (45,10,'5/week');
INSERT INTO ClienteMedicamento VALUES (354,33,'5/week');
INSERT INTO ClienteMedicamento VALUES (344,35,'1/day');
INSERT INTO ClienteMedicamento VALUES (358,1,'4/week');
INSERT INTO ClienteMedicamento VALUES (20,4,'2/day');
INSERT INTO ClienteMedicamento VALUES (757,30,'1/week');
INSERT INTO ClienteMedicamento VALUES (760,6,'5/week');
INSERT INTO ClienteMedicamento VALUES (336,1,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (583,11,'1/day');
INSERT INTO ClienteMedicamento VALUES (380,16,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (19,40,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (833,3,'4/week');
INSERT INTO ClienteMedicamento VALUES (98,31,'1/day');
INSERT INTO ClienteMedicamento VALUES (26,26,'2/day');
INSERT INTO ClienteMedicamento VALUES (125,16,'2/week');
INSERT INTO ClienteMedicamento VALUES (87,11,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (828,15,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (838,37,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (650,37,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (485,9,'5/week');
INSERT INTO ClienteMedicamento VALUES (76,29,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (947,7,'5/week');
INSERT INTO ClienteMedicamento VALUES (506,35,'5/week');
INSERT INTO ClienteMedicamento VALUES (61,29,'4/week');
INSERT INTO ClienteMedicamento VALUES (430,39,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (28,36,'2/week');
INSERT INTO ClienteMedicamento VALUES (66,20,'1/day');
INSERT INTO ClienteMedicamento VALUES (497,13,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (609,23,'4/week');
INSERT INTO ClienteMedicamento VALUES (143,25,'1/day');
INSERT INTO ClienteMedicamento VALUES (274,40,'1/week');
INSERT INTO ClienteMedicamento VALUES (428,33,'2/week');
INSERT INTO ClienteMedicamento VALUES (799,7,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (580,32,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (304,17,'5/week');
INSERT INTO ClienteMedicamento VALUES (207,33,'5/week');
INSERT INTO ClienteMedicamento VALUES (746,5,'4/week');
INSERT INTO ClienteMedicamento VALUES (723,18,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (825,15,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (61,5,'2/day');
INSERT INTO ClienteMedicamento VALUES (213,28,'3/day');
INSERT INTO ClienteMedicamento VALUES (719,27,'2/day');
INSERT INTO ClienteMedicamento VALUES (965,15,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (592,13,'3/week');
INSERT INTO ClienteMedicamento VALUES (165,10,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (345,16,'1/day');
INSERT INTO ClienteMedicamento VALUES (827,35,'5/week');
INSERT INTO ClienteMedicamento VALUES (52,10,'2/week');
INSERT INTO ClienteMedicamento VALUES (103,6,'4/week');
INSERT INTO ClienteMedicamento VALUES (252,27,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (789,16,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (52,9,'4/week');
INSERT INTO ClienteMedicamento VALUES (841,4,'2/week');
INSERT INTO ClienteMedicamento VALUES (675,18,'5/week');
INSERT INTO ClienteMedicamento VALUES (222,25,'3/week');
INSERT INTO ClienteMedicamento VALUES (111,17,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (684,28,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (183,11,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (564,39,'3/day');
INSERT INTO ClienteMedicamento VALUES (536,11,'2/week');
INSERT INTO ClienteMedicamento VALUES (945,19,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (94,22,'1/day');
INSERT INTO ClienteMedicamento VALUES (672,35,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (312,21,'2/day');
INSERT INTO ClienteMedicamento VALUES (451,1,'1/day');
INSERT INTO ClienteMedicamento VALUES (897,2,'2/day');
INSERT INTO ClienteMedicamento VALUES (235,15,'2/day');
INSERT INTO ClienteMedicamento VALUES (681,9,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (405,9,'1/day');
INSERT INTO ClienteMedicamento VALUES (116,23,'1/day');
INSERT INTO ClienteMedicamento VALUES (727,20,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (559,28,'1/day');
INSERT INTO ClienteMedicamento VALUES (684,5,'1/day');
INSERT INTO ClienteMedicamento VALUES (695,33,'2/day');
INSERT INTO ClienteMedicamento VALUES (740,2,'2/week');
INSERT INTO ClienteMedicamento VALUES (346,4,'3/week');
INSERT INTO ClienteMedicamento VALUES (234,18,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (223,29,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (958,12,'5/week');
INSERT INTO ClienteMedicamento VALUES (90,7,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (595,8,'3/day');
INSERT INTO ClienteMedicamento VALUES (382,15,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (28,3,'3/week');
INSERT INTO ClienteMedicamento VALUES (134,33,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (484,11,'2/week');
INSERT INTO ClienteMedicamento VALUES (683,36,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (222,33,'3/day');
INSERT INTO ClienteMedicamento VALUES (179,2,'4/week');
INSERT INTO ClienteMedicamento VALUES (719,38,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (27,24,'3/week');
INSERT INTO ClienteMedicamento VALUES (732,10,'3/day');
INSERT INTO ClienteMedicamento VALUES (529,40,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (314,36,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (250,40,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (856,29,'2/day');
INSERT INTO ClienteMedicamento VALUES (146,35,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (605,39,'3/week');
INSERT INTO ClienteMedicamento VALUES (940,9,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (322,22,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (998,7,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (204,9,'2/day');
INSERT INTO ClienteMedicamento VALUES (392,12,'1/week');
INSERT INTO ClienteMedicamento VALUES (803,3,'1/week');
INSERT INTO ClienteMedicamento VALUES (348,24,'3/day');
INSERT INTO ClienteMedicamento VALUES (964,29,'2/day');
INSERT INTO ClienteMedicamento VALUES (369,15,'3/week');
INSERT INTO ClienteMedicamento VALUES (697,22,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (751,21,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (510,37,'5/week');
INSERT INTO ClienteMedicamento VALUES (78,15,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (865,18,'3/week');
INSERT INTO ClienteMedicamento VALUES (412,22,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (142,2,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (769,3,'3/week');
INSERT INTO ClienteMedicamento VALUES (948,31,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (680,18,'4/week');
INSERT INTO ClienteMedicamento VALUES (946,7,'2/day');
INSERT INTO ClienteMedicamento VALUES (45,18,'1/week');
INSERT INTO ClienteMedicamento VALUES (660,19,'5/week');
INSERT INTO ClienteMedicamento VALUES (16,15,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (697,25,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (862,8,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (903,30,'3/day');
INSERT INTO ClienteMedicamento VALUES (935,37,'1/day');
INSERT INTO ClienteMedicamento VALUES (193,7,'5/week');
INSERT INTO ClienteMedicamento VALUES (93,35,'1/day');
INSERT INTO ClienteMedicamento VALUES (681,31,'2/day');
INSERT INTO ClienteMedicamento VALUES (874,8,'2/day');
INSERT INTO ClienteMedicamento VALUES (655,24,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (503,2,'2/day');
INSERT INTO ClienteMedicamento VALUES (557,5,'2/day');
INSERT INTO ClienteMedicamento VALUES (628,2,'4/week');
INSERT INTO ClienteMedicamento VALUES (188,20,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (646,23,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (634,35,'3/day');
INSERT INTO ClienteMedicamento VALUES (796,6,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (48,15,'1/week');
INSERT INTO ClienteMedicamento VALUES (124,7,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (793,33,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (975,6,'1/week');
INSERT INTO ClienteMedicamento VALUES (779,6,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (127,15,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (55,10,'3/day');
INSERT INTO ClienteMedicamento VALUES (240,4,'5/week');
INSERT INTO ClienteMedicamento VALUES (17,4,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (206,23,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (608,36,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (127,22,'2/day');
INSERT INTO ClienteMedicamento VALUES (598,10,'2/day');
INSERT INTO ClienteMedicamento VALUES (345,18,'1/day');
INSERT INTO ClienteMedicamento VALUES (253,12,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (481,5,'3/week');
INSERT INTO ClienteMedicamento VALUES (631,17,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (900,38,'2/day');
INSERT INTO ClienteMedicamento VALUES (601,31,'5/week');
INSERT INTO ClienteMedicamento VALUES (747,14,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (397,20,'1/week');
INSERT INTO ClienteMedicamento VALUES (842,24,'2/day');
INSERT INTO ClienteMedicamento VALUES (12,24,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (308,33,'5/week');
INSERT INTO ClienteMedicamento VALUES (773,31,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (419,17,'5/week');
INSERT INTO ClienteMedicamento VALUES (295,13,'2/day');
INSERT INTO ClienteMedicamento VALUES (827,22,'3/day');
INSERT INTO ClienteMedicamento VALUES (421,37,'3/day');
INSERT INTO ClienteMedicamento VALUES (750,36,'1/day');
INSERT INTO ClienteMedicamento VALUES (737,5,'2/week');
INSERT INTO ClienteMedicamento VALUES (535,23,'2/week');
INSERT INTO ClienteMedicamento VALUES (962,27,'1/day');
INSERT INTO ClienteMedicamento VALUES (706,11,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (679,6,'1/day');
INSERT INTO ClienteMedicamento VALUES (390,25,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (562,30,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (648,10,'4/week');
INSERT INTO ClienteMedicamento VALUES (594,3,'4/week');
INSERT INTO ClienteMedicamento VALUES (485,34,'5/week');
INSERT INTO ClienteMedicamento VALUES (669,29,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (277,37,'1/week');
INSERT INTO ClienteMedicamento VALUES (173,15,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (768,17,'5/week');
INSERT INTO ClienteMedicamento VALUES (866,5,'4/week');
INSERT INTO ClienteMedicamento VALUES (908,13,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (5,25,'2/week');
INSERT INTO ClienteMedicamento VALUES (723,14,'3/day');
INSERT INTO ClienteMedicamento VALUES (545,36,'3/day');
INSERT INTO ClienteMedicamento VALUES (768,39,'5/week');
INSERT INTO ClienteMedicamento VALUES (380,14,'2/week');
INSERT INTO ClienteMedicamento VALUES (185,22,'2/week');
INSERT INTO ClienteMedicamento VALUES (168,29,'5/week');
INSERT INTO ClienteMedicamento VALUES (709,37,'5/week');
INSERT INTO ClienteMedicamento VALUES (160,6,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (776,17,'1/week');
INSERT INTO ClienteMedicamento VALUES (316,31,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (727,36,'3/day');
INSERT INTO ClienteMedicamento VALUES (166,21,'1/week');
INSERT INTO ClienteMedicamento VALUES (596,33,'3/day');
INSERT INTO ClienteMedicamento VALUES (210,16,'3/week');
INSERT INTO ClienteMedicamento VALUES (106,28,'2/week');
INSERT INTO ClienteMedicamento VALUES (548,17,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (223,36,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (238,24,'3/week');
INSERT INTO ClienteMedicamento VALUES (182,5,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (27,30,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (129,26,'4/week');
INSERT INTO ClienteMedicamento VALUES (723,30,'2/day');
INSERT INTO ClienteMedicamento VALUES (508,19,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (976,7,'1/week');
INSERT INTO ClienteMedicamento VALUES (76,19,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (653,6,'2/day');
INSERT INTO ClienteMedicamento VALUES (879,14,'4/week');
INSERT INTO ClienteMedicamento VALUES (76,9,'4/week');
INSERT INTO ClienteMedicamento VALUES (808,27,'2/week');
INSERT INTO ClienteMedicamento VALUES (579,31,'5/week');
INSERT INTO ClienteMedicamento VALUES (634,14,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (532,11,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (338,39,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (629,28,'3/day');
INSERT INTO ClienteMedicamento VALUES (305,11,'3/day');
INSERT INTO ClienteMedicamento VALUES (159,26,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (730,36,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (713,34,'3/week');
INSERT INTO ClienteMedicamento VALUES (134,29,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (464,34,'2/day');
INSERT INTO ClienteMedicamento VALUES (643,40,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (367,16,'4/week');
INSERT INTO ClienteMedicamento VALUES (400,32,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (690,34,'5/week');
INSERT INTO ClienteMedicamento VALUES (357,24,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (21,26,'3/week');
INSERT INTO ClienteMedicamento VALUES (478,32,'1/week');
INSERT INTO ClienteMedicamento VALUES (190,29,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (949,34,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (740,40,'1/day');
INSERT INTO ClienteMedicamento VALUES (624,2,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (993,18,'5/week');
INSERT INTO ClienteMedicamento VALUES (329,6,'1/week');
INSERT INTO ClienteMedicamento VALUES (504,15,'2/week');
INSERT INTO ClienteMedicamento VALUES (568,30,'2/week');
INSERT INTO ClienteMedicamento VALUES (550,25,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (207,39,'4/week');
INSERT INTO ClienteMedicamento VALUES (694,20,'3/week');
INSERT INTO ClienteMedicamento VALUES (705,18,'3/week');
INSERT INTO ClienteMedicamento VALUES (757,20,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (724,23,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (867,12,'5/week');
INSERT INTO ClienteMedicamento VALUES (43,22,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (806,18,'2/week');
INSERT INTO ClienteMedicamento VALUES (771,22,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (342,20,'2/week');
INSERT INTO ClienteMedicamento VALUES (304,14,'2/week');
INSERT INTO ClienteMedicamento VALUES (633,35,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (99,24,'4/week');
INSERT INTO ClienteMedicamento VALUES (864,12,'4/week');
INSERT INTO ClienteMedicamento VALUES (86,11,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (77,10,'4/week');
INSERT INTO ClienteMedicamento VALUES (998,11,'1/week');
INSERT INTO ClienteMedicamento VALUES (863,7,'3/week');
INSERT INTO ClienteMedicamento VALUES (781,34,'2/week');
INSERT INTO ClienteMedicamento VALUES (777,19,'2/week');
INSERT INTO ClienteMedicamento VALUES (14,12,'5/week');
INSERT INTO ClienteMedicamento VALUES (233,31,'3/day');
INSERT INTO ClienteMedicamento VALUES (783,35,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (230,40,'5/week');
INSERT INTO ClienteMedicamento VALUES (148,17,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (224,17,'1/day');
INSERT INTO ClienteMedicamento VALUES (254,20,'5/week');
INSERT INTO ClienteMedicamento VALUES (410,13,'1/day');
INSERT INTO ClienteMedicamento VALUES (390,34,'2/week');
INSERT INTO ClienteMedicamento VALUES (18,18,'3/week');
INSERT INTO ClienteMedicamento VALUES (773,5,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (324,1,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (785,3,'1/week');
INSERT INTO ClienteMedicamento VALUES (23,22,'2/week');
INSERT INTO ClienteMedicamento VALUES (385,12,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (890,9,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (620,22,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (491,35,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (230,9,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (777,27,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (721,38,'4/week');
INSERT INTO ClienteMedicamento VALUES (845,35,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (722,2,'5/week');
INSERT INTO ClienteMedicamento VALUES (68,40,'3/week');
INSERT INTO ClienteMedicamento VALUES (677,1,'5/week');
INSERT INTO ClienteMedicamento VALUES (959,19,'1/week');
INSERT INTO ClienteMedicamento VALUES (373,4,'2/day');
INSERT INTO ClienteMedicamento VALUES (648,29,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (383,23,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (536,5,'2/day');
INSERT INTO ClienteMedicamento VALUES (439,16,'2/day');
INSERT INTO ClienteMedicamento VALUES (651,35,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (734,19,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (831,7,'1/day');
INSERT INTO ClienteMedicamento VALUES (257,36,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (474,20,'3/week');
INSERT INTO ClienteMedicamento VALUES (769,2,'1/day');
INSERT INTO ClienteMedicamento VALUES (275,15,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (808,24,'5/week');
INSERT INTO ClienteMedicamento VALUES (414,1,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (118,4,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (610,20,'2/week');
INSERT INTO ClienteMedicamento VALUES (846,38,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (766,29,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (282,26,'4/week');
INSERT INTO ClienteMedicamento VALUES (88,14,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (469,24,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (714,14,'1/day');
INSERT INTO ClienteMedicamento VALUES (250,22,'3/day');
INSERT INTO ClienteMedicamento VALUES (993,37,'3/day');
INSERT INTO ClienteMedicamento VALUES (799,2,'1/day');
INSERT INTO ClienteMedicamento VALUES (164,38,'2/week');
INSERT INTO ClienteMedicamento VALUES (454,3,'3/day');
INSERT INTO ClienteMedicamento VALUES (741,25,'2/week');
INSERT INTO ClienteMedicamento VALUES (144,12,'2/week');
INSERT INTO ClienteMedicamento VALUES (356,33,'3/day');
INSERT INTO ClienteMedicamento VALUES (389,17,'3/day');
INSERT INTO ClienteMedicamento VALUES (731,4,'4/week');
INSERT INTO ClienteMedicamento VALUES (596,21,'1/week');
INSERT INTO ClienteMedicamento VALUES (740,32,'2/day');
INSERT INTO ClienteMedicamento VALUES (229,38,'4/week');
INSERT INTO ClienteMedicamento VALUES (663,7,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (675,20,'2/week');
INSERT INTO ClienteMedicamento VALUES (347,22,'1/day');
INSERT INTO ClienteMedicamento VALUES (227,3,'2/week');
INSERT INTO ClienteMedicamento VALUES (244,34,'1/week');
INSERT INTO ClienteMedicamento VALUES (321,12,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (731,10,'1/week');
INSERT INTO ClienteMedicamento VALUES (244,37,'2/week');
INSERT INTO ClienteMedicamento VALUES (408,39,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (994,22,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (131,15,'2/day');
INSERT INTO ClienteMedicamento VALUES (352,6,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (121,10,'2/day');
INSERT INTO ClienteMedicamento VALUES (661,3,'3/day');
INSERT INTO ClienteMedicamento VALUES (335,15,'1/day');
INSERT INTO ClienteMedicamento VALUES (504,36,'1/day');
INSERT INTO ClienteMedicamento VALUES (392,15,'1/week');
INSERT INTO ClienteMedicamento VALUES (866,35,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (610,9,'2/day');
INSERT INTO ClienteMedicamento VALUES (355,21,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (157,14,'2/day');
INSERT INTO ClienteMedicamento VALUES (236,32,'4/week');
INSERT INTO ClienteMedicamento VALUES (770,5,'3/day');
INSERT INTO ClienteMedicamento VALUES (251,36,'3/day');
INSERT INTO ClienteMedicamento VALUES (250,34,'3/week');
INSERT INTO ClienteMedicamento VALUES (634,29,'4/week');
INSERT INTO ClienteMedicamento VALUES (837,16,'3/day');
INSERT INTO ClienteMedicamento VALUES (256,1,'2/day');
INSERT INTO ClienteMedicamento VALUES (40,6,'1/week');
INSERT INTO ClienteMedicamento VALUES (238,1,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (736,3,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (842,33,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (773,2,'2/week');
INSERT INTO ClienteMedicamento VALUES (906,40,'2/week');
INSERT INTO ClienteMedicamento VALUES (531,18,'1/week');
INSERT INTO ClienteMedicamento VALUES (172,5,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (1000,13,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (645,14,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (780,25,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (282,1,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (35,26,'3/week');
INSERT INTO ClienteMedicamento VALUES (39,35,'3/day');
INSERT INTO ClienteMedicamento VALUES (121,9,'1/week');
INSERT INTO ClienteMedicamento VALUES (813,25,'3/week');
INSERT INTO ClienteMedicamento VALUES (670,4,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (157,30,'2/week');
INSERT INTO ClienteMedicamento VALUES (45,35,'3/day');
INSERT INTO ClienteMedicamento VALUES (576,35,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (776,25,'3/day');
INSERT INTO ClienteMedicamento VALUES (758,31,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (482,33,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (536,17,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (823,11,'5/week');
INSERT INTO ClienteMedicamento VALUES (564,20,'1/week');
INSERT INTO ClienteMedicamento VALUES (843,12,'2/day');
INSERT INTO ClienteMedicamento VALUES (472,39,'3/week');
INSERT INTO ClienteMedicamento VALUES (13,30,'1/week');
INSERT INTO ClienteMedicamento VALUES (240,22,'3/day');
INSERT INTO ClienteMedicamento VALUES (212,32,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (706,37,'3/day');
INSERT INTO ClienteMedicamento VALUES (739,18,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (328,36,'3/day');
INSERT INTO ClienteMedicamento VALUES (189,13,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (829,6,'4/week');
INSERT INTO ClienteMedicamento VALUES (89,34,'1/week');
INSERT INTO ClienteMedicamento VALUES (244,4,'1/week');
INSERT INTO ClienteMedicamento VALUES (127,39,'3/day');
INSERT INTO ClienteMedicamento VALUES (17,32,'4/week');
INSERT INTO ClienteMedicamento VALUES (72,25,'2/day');
INSERT INTO ClienteMedicamento VALUES (259,11,'2/day');
INSERT INTO ClienteMedicamento VALUES (744,28,'1/week');
INSERT INTO ClienteMedicamento VALUES (714,29,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (570,21,'4/week');
INSERT INTO ClienteMedicamento VALUES (429,32,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (802,27,'1/day');
INSERT INTO ClienteMedicamento VALUES (87,28,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (571,13,'5/week');
INSERT INTO ClienteMedicamento VALUES (633,8,'1/day');
INSERT INTO ClienteMedicamento VALUES (893,28,'3/day');
INSERT INTO ClienteMedicamento VALUES (408,6,'3/day');
INSERT INTO ClienteMedicamento VALUES (635,25,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (480,3,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (704,28,'2/week');
INSERT INTO ClienteMedicamento VALUES (125,15,'5/week');
INSERT INTO ClienteMedicamento VALUES (828,37,'4/week');
INSERT INTO ClienteMedicamento VALUES (364,15,'2/week');
INSERT INTO ClienteMedicamento VALUES (202,3,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (693,35,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (713,38,'2/week');
INSERT INTO ClienteMedicamento VALUES (710,35,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (334,14,'2/week');
INSERT INTO ClienteMedicamento VALUES (828,30,'1/week');
INSERT INTO ClienteMedicamento VALUES (833,30,'1/day');
INSERT INTO ClienteMedicamento VALUES (550,5,'3/week');
INSERT INTO ClienteMedicamento VALUES (535,25,'5/week');
INSERT INTO ClienteMedicamento VALUES (841,5,'5/week');
INSERT INTO ClienteMedicamento VALUES (58,8,'1/week');
INSERT INTO ClienteMedicamento VALUES (408,33,'2/week');
INSERT INTO ClienteMedicamento VALUES (929,11,'4/week');
INSERT INTO ClienteMedicamento VALUES (371,3,'4/week');
INSERT INTO ClienteMedicamento VALUES (524,9,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (133,16,'2/week');
INSERT INTO ClienteMedicamento VALUES (856,13,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (35,34,'2/week');
INSERT INTO ClienteMedicamento VALUES (919,37,'2/day');
INSERT INTO ClienteMedicamento VALUES (551,1,'3/week');
INSERT INTO ClienteMedicamento VALUES (943,26,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (556,3,'2/week');
INSERT INTO ClienteMedicamento VALUES (517,5,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (945,6,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (298,15,'1/week');
INSERT INTO ClienteMedicamento VALUES (6,28,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (936,18,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (401,16,'4/week');
INSERT INTO ClienteMedicamento VALUES (578,23,'2/week');
INSERT INTO ClienteMedicamento VALUES (306,27,'2/day');
INSERT INTO ClienteMedicamento VALUES (382,16,'2/week');
INSERT INTO ClienteMedicamento VALUES (694,18,'3/week');
INSERT INTO ClienteMedicamento VALUES (941,40,'2/week');
INSERT INTO ClienteMedicamento VALUES (67,31,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (195,30,'3/week');
INSERT INTO ClienteMedicamento VALUES (76,40,'3/week');
INSERT INTO ClienteMedicamento VALUES (6,6,'4/week');
INSERT INTO ClienteMedicamento VALUES (208,12,'3/day');
INSERT INTO ClienteMedicamento VALUES (541,34,'3/day');
INSERT INTO ClienteMedicamento VALUES (870,29,'4/week');
INSERT INTO ClienteMedicamento VALUES (561,19,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (912,25,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (659,35,'1/day');
INSERT INTO ClienteMedicamento VALUES (47,26,'2/week');
INSERT INTO ClienteMedicamento VALUES (406,21,'5/week');
INSERT INTO ClienteMedicamento VALUES (579,19,'1/day');
INSERT INTO ClienteMedicamento VALUES (44,5,'4/week');
INSERT INTO ClienteMedicamento VALUES (170,38,'3/day');
INSERT INTO ClienteMedicamento VALUES (847,28,'1/day');
INSERT INTO ClienteMedicamento VALUES (708,24,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (633,25,'5/week');
INSERT INTO ClienteMedicamento VALUES (950,34,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (498,37,'1/week');
INSERT INTO ClienteMedicamento VALUES (892,35,'2/week');
INSERT INTO ClienteMedicamento VALUES (355,3,'3/week');
INSERT INTO ClienteMedicamento VALUES (123,22,'3/day');
INSERT INTO ClienteMedicamento VALUES (443,25,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (432,20,'1/day');
INSERT INTO ClienteMedicamento VALUES (518,11,'2/day');
INSERT INTO ClienteMedicamento VALUES (161,21,'3/week');
INSERT INTO ClienteMedicamento VALUES (503,14,'2/week');
INSERT INTO ClienteMedicamento VALUES (998,36,'3/week');
INSERT INTO ClienteMedicamento VALUES (818,10,'2/week');
INSERT INTO ClienteMedicamento VALUES (710,25,'3/day');
INSERT INTO ClienteMedicamento VALUES (204,16,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (19,6,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (481,12,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (461,30,'3/day');
INSERT INTO ClienteMedicamento VALUES (119,23,'1/day');
INSERT INTO ClienteMedicamento VALUES (154,16,'3/day');
INSERT INTO ClienteMedicamento VALUES (402,36,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (790,31,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (404,16,'3/week');
INSERT INTO ClienteMedicamento VALUES (883,38,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (164,14,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (947,34,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (770,1,'2/day');
INSERT INTO ClienteMedicamento VALUES (614,25,'1/day');
INSERT INTO ClienteMedicamento VALUES (562,20,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (191,8,'3/week');
INSERT INTO ClienteMedicamento VALUES (393,22,'1/day');
INSERT INTO ClienteMedicamento VALUES (289,26,'4/week');
INSERT INTO ClienteMedicamento VALUES (473,21,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (746,17,'1/week');
INSERT INTO ClienteMedicamento VALUES (914,3,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (536,4,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (816,22,'1/day');
INSERT INTO ClienteMedicamento VALUES (305,38,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (671,35,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (859,34,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (826,2,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (356,26,'2/day');
INSERT INTO ClienteMedicamento VALUES (572,9,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (466,12,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (150,11,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (324,2,'2/week');
INSERT INTO ClienteMedicamento VALUES (842,1,'1/day');
INSERT INTO ClienteMedicamento VALUES (627,13,'2/week');
INSERT INTO ClienteMedicamento VALUES (598,40,'3/week');
INSERT INTO ClienteMedicamento VALUES (202,30,'4/week');
INSERT INTO ClienteMedicamento VALUES (43,14,'3/week');
INSERT INTO ClienteMedicamento VALUES (71,25,'1/day');
INSERT INTO ClienteMedicamento VALUES (688,31,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (145,13,'2/day');
INSERT INTO ClienteMedicamento VALUES (140,40,'1/week');
INSERT INTO ClienteMedicamento VALUES (355,17,'3/week');
INSERT INTO ClienteMedicamento VALUES (592,32,'1/day');
INSERT INTO ClienteMedicamento VALUES (787,30,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (631,29,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (86,40,'2/day');
INSERT INTO ClienteMedicamento VALUES (697,39,'1/week');
INSERT INTO ClienteMedicamento VALUES (710,12,'4/week');
INSERT INTO ClienteMedicamento VALUES (40,29,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (909,32,'5/week');
INSERT INTO ClienteMedicamento VALUES (845,29,'1/day');
INSERT INTO ClienteMedicamento VALUES (94,15,'1/day');
INSERT INTO ClienteMedicamento VALUES (509,24,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (968,26,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (221,40,'2/day');
INSERT INTO ClienteMedicamento VALUES (25,2,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (444,32,'5/week');
INSERT INTO ClienteMedicamento VALUES (283,32,'1/day');
INSERT INTO ClienteMedicamento VALUES (307,11,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (568,28,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (545,33,'2/week');
INSERT INTO ClienteMedicamento VALUES (895,29,'4/week');
INSERT INTO ClienteMedicamento VALUES (34,18,'5/week');
INSERT INTO ClienteMedicamento VALUES (932,37,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (676,15,'1/week');
INSERT INTO ClienteMedicamento VALUES (34,10,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (129,37,'3/day');
INSERT INTO ClienteMedicamento VALUES (904,39,'5/week');
INSERT INTO ClienteMedicamento VALUES (546,8,'5/week');
INSERT INTO ClienteMedicamento VALUES (83,39,'1/week');
INSERT INTO ClienteMedicamento VALUES (511,16,'1/week');
INSERT INTO ClienteMedicamento VALUES (764,15,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (682,35,'3/day');
INSERT INTO ClienteMedicamento VALUES (806,23,'3/week');
INSERT INTO ClienteMedicamento VALUES (349,36,'4/week');
INSERT INTO ClienteMedicamento VALUES (950,4,'2/day');
INSERT INTO ClienteMedicamento VALUES (529,9,'3/day');
INSERT INTO ClienteMedicamento VALUES (412,34,'3/day');
INSERT INTO ClienteMedicamento VALUES (410,21,'3/week');
INSERT INTO ClienteMedicamento VALUES (405,8,'3/day');
INSERT INTO ClienteMedicamento VALUES (100,30,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (112,2,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (277,22,'2/day');
INSERT INTO ClienteMedicamento VALUES (425,6,'2/day');
INSERT INTO ClienteMedicamento VALUES (478,33,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (227,20,'5/week');
INSERT INTO ClienteMedicamento VALUES (918,31,'2/day');
INSERT INTO ClienteMedicamento VALUES (526,1,'3/day');
INSERT INTO ClienteMedicamento VALUES (792,33,'4/week');
INSERT INTO ClienteMedicamento VALUES (807,18,'1/day');
INSERT INTO ClienteMedicamento VALUES (711,6,'3/week');
INSERT INTO ClienteMedicamento VALUES (107,8,'2/day');
INSERT INTO ClienteMedicamento VALUES (657,38,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (946,11,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (320,27,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (255,16,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (955,33,'2/day');
INSERT INTO ClienteMedicamento VALUES (275,31,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (569,23,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (279,27,'2/week');
INSERT INTO ClienteMedicamento VALUES (876,4,'5/week');
INSERT INTO ClienteMedicamento VALUES (736,28,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (944,39,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (390,40,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (541,10,'4/week');
INSERT INTO ClienteMedicamento VALUES (319,30,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (295,36,'1/week');
INSERT INTO ClienteMedicamento VALUES (614,32,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (984,1,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (215,38,'3/day');
INSERT INTO ClienteMedicamento VALUES (744,30,'3/day');
INSERT INTO ClienteMedicamento VALUES (637,33,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (54,6,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (486,40,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (78,36,'4/week');
INSERT INTO ClienteMedicamento VALUES (280,9,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (477,3,'4/week');
INSERT INTO ClienteMedicamento VALUES (556,13,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (652,36,'4/week');
INSERT INTO ClienteMedicamento VALUES (297,21,'3/week');
INSERT INTO ClienteMedicamento VALUES (26,29,'5/week');
INSERT INTO ClienteMedicamento VALUES (615,4,'2/day');
INSERT INTO ClienteMedicamento VALUES (616,19,'4/week');
INSERT INTO ClienteMedicamento VALUES (378,15,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (383,18,'4/week');
INSERT INTO ClienteMedicamento VALUES (400,36,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (770,25,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (375,32,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (566,1,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (386,39,'4/week');
INSERT INTO ClienteMedicamento VALUES (167,3,'3/week');
INSERT INTO ClienteMedicamento VALUES (976,23,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (331,24,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (75,7,'1/week');
INSERT INTO ClienteMedicamento VALUES (466,13,'2/week');
INSERT INTO ClienteMedicamento VALUES (489,9,'1/day');
INSERT INTO ClienteMedicamento VALUES (550,27,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (10,22,'1/day');
INSERT INTO ClienteMedicamento VALUES (142,19,'2/week');
INSERT INTO ClienteMedicamento VALUES (23,4,'4/week');
INSERT INTO ClienteMedicamento VALUES (666,9,'3/day');
INSERT INTO ClienteMedicamento VALUES (842,26,'3/week');
INSERT INTO ClienteMedicamento VALUES (800,2,'2/day');
INSERT INTO ClienteMedicamento VALUES (16,23,'3/day');
INSERT INTO ClienteMedicamento VALUES (39,22,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (433,6,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (663,16,'3/week');
INSERT INTO ClienteMedicamento VALUES (869,36,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (549,3,'2/week');
INSERT INTO ClienteMedicamento VALUES (551,4,'3/day');
INSERT INTO ClienteMedicamento VALUES (727,23,'3/day');
INSERT INTO ClienteMedicamento VALUES (355,19,'2/week');
INSERT INTO ClienteMedicamento VALUES (103,29,'1/day');
INSERT INTO ClienteMedicamento VALUES (830,4,'4/week');
INSERT INTO ClienteMedicamento VALUES (399,22,'5/week');
INSERT INTO ClienteMedicamento VALUES (609,2,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (880,39,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (16,32,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (688,16,'1/week');
INSERT INTO ClienteMedicamento VALUES (708,35,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (257,8,'2/week');
INSERT INTO ClienteMedicamento VALUES (978,34,'3/week');
INSERT INTO ClienteMedicamento VALUES (440,32,'3/day');
INSERT INTO ClienteMedicamento VALUES (552,6,'2/week');
INSERT INTO ClienteMedicamento VALUES (320,36,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (177,29,'1/day');
INSERT INTO ClienteMedicamento VALUES (334,33,'2/week');
INSERT INTO ClienteMedicamento VALUES (600,17,'1/day');
INSERT INTO ClienteMedicamento VALUES (399,14,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (678,23,'3/day');
INSERT INTO ClienteMedicamento VALUES (198,19,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (690,32,'2/day');
INSERT INTO ClienteMedicamento VALUES (441,17,'2/day');
INSERT INTO ClienteMedicamento VALUES (207,3,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (494,15,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (334,31,'5/week');
INSERT INTO ClienteMedicamento VALUES (614,35,'2/day');
INSERT INTO ClienteMedicamento VALUES (407,31,'1/week');
INSERT INTO ClienteMedicamento VALUES (95,22,'3/week');
INSERT INTO ClienteMedicamento VALUES (862,32,'1/week');
INSERT INTO ClienteMedicamento VALUES (7,14,'2/week');
INSERT INTO ClienteMedicamento VALUES (295,7,'5/week');
INSERT INTO ClienteMedicamento VALUES (270,22,'3/day');
INSERT INTO ClienteMedicamento VALUES (694,10,'1/day');
INSERT INTO ClienteMedicamento VALUES (13,1,'3/day');
INSERT INTO ClienteMedicamento VALUES (217,8,'1/week');
INSERT INTO ClienteMedicamento VALUES (541,14,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (499,3,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (660,14,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (933,38,'1/week');
INSERT INTO ClienteMedicamento VALUES (782,4,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (856,25,'1/day');
INSERT INTO ClienteMedicamento VALUES (496,15,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (670,39,'3/day');
INSERT INTO ClienteMedicamento VALUES (558,35,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (348,10,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (80,15,'2/day');
INSERT INTO ClienteMedicamento VALUES (536,9,'5/week');
INSERT INTO ClienteMedicamento VALUES (202,9,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (19,10,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (369,12,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (719,9,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (164,39,'2/week');
INSERT INTO ClienteMedicamento VALUES (150,1,'3/day');
INSERT INTO ClienteMedicamento VALUES (368,8,'2/day');
INSERT INTO ClienteMedicamento VALUES (251,37,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (464,14,'2/day');
INSERT INTO ClienteMedicamento VALUES (486,14,'3/day');
INSERT INTO ClienteMedicamento VALUES (132,21,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (460,14,'1/week');
INSERT INTO ClienteMedicamento VALUES (596,26,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (103,31,'3/day');
INSERT INTO ClienteMedicamento VALUES (302,27,'3/day');
INSERT INTO ClienteMedicamento VALUES (729,5,'3/week');
INSERT INTO ClienteMedicamento VALUES (324,14,'2/week');
INSERT INTO ClienteMedicamento VALUES (26,34,'5/week');
INSERT INTO ClienteMedicamento VALUES (923,35,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (439,12,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (760,9,'1/day');
INSERT INTO ClienteMedicamento VALUES (821,40,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (25,12,'5/week');
INSERT INTO ClienteMedicamento VALUES (123,28,'3/week');
INSERT INTO ClienteMedicamento VALUES (628,34,'2/day');
INSERT INTO ClienteMedicamento VALUES (675,3,'2/week');
INSERT INTO ClienteMedicamento VALUES (859,35,'5/week');
INSERT INTO ClienteMedicamento VALUES (69,35,'4/week');
INSERT INTO ClienteMedicamento VALUES (445,28,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (692,28,'2/week');
INSERT INTO ClienteMedicamento VALUES (750,26,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (27,4,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (13,29,'4/week');
INSERT INTO ClienteMedicamento VALUES (427,7,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (481,6,'1/day');
INSERT INTO ClienteMedicamento VALUES (536,24,'4/week');
INSERT INTO ClienteMedicamento VALUES (316,23,'3/week');
INSERT INTO ClienteMedicamento VALUES (671,13,'5/week');
INSERT INTO ClienteMedicamento VALUES (103,25,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (739,40,'3/week');
INSERT INTO ClienteMedicamento VALUES (439,8,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (896,10,'3/day');
INSERT INTO ClienteMedicamento VALUES (823,6,'5/week');
INSERT INTO ClienteMedicamento VALUES (357,22,'5/week');
INSERT INTO ClienteMedicamento VALUES (852,29,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (265,26,'3/week');
INSERT INTO ClienteMedicamento VALUES (959,32,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (501,15,'5/week');
INSERT INTO ClienteMedicamento VALUES (754,28,'3/day');
INSERT INTO ClienteMedicamento VALUES (988,2,'3/week');
INSERT INTO ClienteMedicamento VALUES (883,19,'4/week');
INSERT INTO ClienteMedicamento VALUES (549,39,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (948,24,'3/day');
INSERT INTO ClienteMedicamento VALUES (721,10,'2/day');
INSERT INTO ClienteMedicamento VALUES (528,16,'4/week');
INSERT INTO ClienteMedicamento VALUES (322,39,'1/week');
INSERT INTO ClienteMedicamento VALUES (571,35,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (701,16,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (941,19,'3/day');
INSERT INTO ClienteMedicamento VALUES (324,8,'3/day');
INSERT INTO ClienteMedicamento VALUES (912,30,'1/week');
INSERT INTO ClienteMedicamento VALUES (40,20,'1/day');
INSERT INTO ClienteMedicamento VALUES (675,32,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (752,1,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (338,25,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (646,40,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (296,12,'2/day');
INSERT INTO ClienteMedicamento VALUES (969,25,'5/week');
INSERT INTO ClienteMedicamento VALUES (935,31,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (268,10,'4/week');
INSERT INTO ClienteMedicamento VALUES (211,29,'1/week');
INSERT INTO ClienteMedicamento VALUES (700,19,'3/day');
INSERT INTO ClienteMedicamento VALUES (827,36,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (450,9,'3/day');
INSERT INTO ClienteMedicamento VALUES (906,20,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (647,14,'2/day');
INSERT INTO ClienteMedicamento VALUES (737,21,'2/day');
INSERT INTO ClienteMedicamento VALUES (955,6,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (834,40,'2/day');
INSERT INTO ClienteMedicamento VALUES (925,16,'2/week');
INSERT INTO ClienteMedicamento VALUES (117,40,'1/week');
INSERT INTO ClienteMedicamento VALUES (653,36,'3/day');
INSERT INTO ClienteMedicamento VALUES (971,22,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (865,38,'2/day');
INSERT INTO ClienteMedicamento VALUES (959,34,'5/week');
INSERT INTO ClienteMedicamento VALUES (894,9,'1/week');
INSERT INTO ClienteMedicamento VALUES (801,38,'3/week');
INSERT INTO ClienteMedicamento VALUES (185,6,'2/day');
INSERT INTO ClienteMedicamento VALUES (10,8,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (356,32,'3/day');
INSERT INTO ClienteMedicamento VALUES (505,3,'2/week');
INSERT INTO ClienteMedicamento VALUES (684,20,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (241,10,'1/day');
INSERT INTO ClienteMedicamento VALUES (583,19,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (461,17,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (922,8,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (805,21,'4/week');
INSERT INTO ClienteMedicamento VALUES (73,25,'1/day');
INSERT INTO ClienteMedicamento VALUES (835,9,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (820,18,'5/week');
INSERT INTO ClienteMedicamento VALUES (798,14,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (867,15,'3/week');
INSERT INTO ClienteMedicamento VALUES (786,35,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (718,15,'2/day');
INSERT INTO ClienteMedicamento VALUES (48,29,'2/day');
INSERT INTO ClienteMedicamento VALUES (912,35,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (558,14,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (352,9,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (713,31,'2/day');
INSERT INTO ClienteMedicamento VALUES (371,12,'2/day');
INSERT INTO ClienteMedicamento VALUES (979,17,'3/day');
INSERT INTO ClienteMedicamento VALUES (973,7,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (851,5,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (140,39,'5/week');
INSERT INTO ClienteMedicamento VALUES (879,21,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (624,26,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (175,35,'1/day');
INSERT INTO ClienteMedicamento VALUES (333,8,'2/day');
INSERT INTO ClienteMedicamento VALUES (790,33,'3/week');
INSERT INTO ClienteMedicamento VALUES (493,14,'5/week');
INSERT INTO ClienteMedicamento VALUES (744,34,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (546,15,'2/day');
INSERT INTO ClienteMedicamento VALUES (839,20,'2/week');
INSERT INTO ClienteMedicamento VALUES (811,10,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (897,20,'5/week');
INSERT INTO ClienteMedicamento VALUES (763,19,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (13,23,'5/week');
INSERT INTO ClienteMedicamento VALUES (324,13,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (107,17,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (499,10,'3/week');
INSERT INTO ClienteMedicamento VALUES (553,30,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (112,23,'3/week');
INSERT INTO ClienteMedicamento VALUES (843,15,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (781,4,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (754,34,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (103,33,'3/day');
INSERT INTO ClienteMedicamento VALUES (636,38,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (222,23,'2/week');
INSERT INTO ClienteMedicamento VALUES (255,20,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (275,24,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (934,18,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (353,14,'1/day');
INSERT INTO ClienteMedicamento VALUES (313,16,'4/week');
INSERT INTO ClienteMedicamento VALUES (893,18,'2/week');
INSERT INTO ClienteMedicamento VALUES (190,27,'1 after any meal');
INSERT INTO ClienteMedicamento VALUES (887,15,'1/week');
INSERT INTO ClienteMedicamento VALUES (644,1,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (249,29,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (348,4,'1/day');
INSERT INTO ClienteMedicamento VALUES (229,29,'2/day');
INSERT INTO ClienteMedicamento VALUES (674,22,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (390,9,'4/week');
INSERT INTO ClienteMedicamento VALUES (896,8,'2/day');
INSERT INTO ClienteMedicamento VALUES (666,30,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (399,30,'1/day');
INSERT INTO ClienteMedicamento VALUES (689,15,'1/day');
INSERT INTO ClienteMedicamento VALUES (946,17,'3/week');
INSERT INTO ClienteMedicamento VALUES (727,7,'3/week');
INSERT INTO ClienteMedicamento VALUES (938,13,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (525,19,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (161,13,'1/week');
INSERT INTO ClienteMedicamento VALUES (846,24,'1/week');
INSERT INTO ClienteMedicamento VALUES (756,11,'2/week');
INSERT INTO ClienteMedicamento VALUES (563,5,'2 after any meals (Different meals)');
INSERT INTO ClienteMedicamento VALUES (63,35,'5/week');
INSERT INTO ClienteMedicamento VALUES (825,10,'1/day');
INSERT INTO ClienteMedicamento VALUES (539,13,'4/week');
INSERT INTO ClienteMedicamento VALUES (811,5,'5/week');
INSERT INTO ClienteMedicamento VALUES (953,5,'1 in the morning');
INSERT INTO ClienteMedicamento VALUES (488,11,'1 after waking up, 1 before going to sleep');
INSERT INTO ClienteMedicamento VALUES (228,4,'1 before bed');
INSERT INTO ClienteMedicamento VALUES (530,7,'2 after any meals (Different meals)');
