-- titulo:
-- (Doctor, Nurse, Clinical assistant, Patient services assistant)

-- area_especializacao:
-- (Anesthesiology, Dermatology, Endocrinology, General Medicine, General Surgery,
-- Imaging, Internal Medicine, Nefrology, Neuropsychology, Nutrition, Orthopaedics, 
-- Physical and Rehabilitation Medicine, Proctology, Psychology, Rheumatology, Urology, Cardiology,
-- General Practice, Gynaecology, Immunohemotherapy, Maxillofacial Surgery, Neurology, Neurosurgery,
-- Ophthalmology, Otolaryngology, Plastic and Reconstructive Surgery, Psychiatry, Pulmonology,
-- Speech Therapy, Vascular Surgery)

-- insert 1000 rows

INSERT INTO Empregado VALUES (1,'Jakeem Coffey','Doctor','Ophthalmology');
INSERT INTO Empregado VALUES (2,'Heather Hopkins','Doctor','General Medicine');
INSERT INTO Empregado VALUES (3,'Barclay Frye','Clinical assistent','Neurosurgery');
INSERT INTO Empregado VALUES (4,'Jenna Bridges','Doctor','Nefrology');
INSERT INTO Empregado VALUES (5,'Dorothy Dudley','Patient services assistent','Endocrinology');
INSERT INTO Empregado VALUES (6,'Kiayada Pierce','Patient services assistent','Psychiatry');
INSERT INTO Empregado VALUES (7,'Leila Collier','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (8,'Angelica Kemp','Clinical assistent','Dermatology');
INSERT INTO Empregado VALUES (9,'Holly Ratliff','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (10,'Jasper Pruitt','Patient services assistent','General Medicine');
INSERT INTO Empregado VALUES (11,'Kato William','Clinical assistent','Cardiology');
INSERT INTO Empregado VALUES (12,'Chester Quinn','Nurse','Gynaecology');
INSERT INTO Empregado VALUES (13,'Lance Doyle','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (14,'Yoshio Hull','Clinical assistent','General Surgery');
INSERT INTO Empregado VALUES (15,'Ashton Ramsey','Patient services assistent','Gynaecology');
INSERT INTO Empregado VALUES (16,'Emi Burks','Nurse','Psychiatry');
INSERT INTO Empregado VALUES (17,'Pearl Delacruz','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (18,'Jescie Mcdaniel','Patient services assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (19,'Isadora Livingston','Nurse','Anesthesiology');
INSERT INTO Empregado VALUES (20,'Amela Newman','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (21,'Nasim Stanton','Doctor','Anesthesiology');
INSERT INTO Empregado VALUES (22,'Alfonso Wood','Clinical assistent','Pulmonology');
INSERT INTO Empregado VALUES (23,'Dylan Miles','Clinical assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (24,'Timothy Zamora','Patient services assistent','Proctology');
INSERT INTO Empregado VALUES (25,'Kylan Dunlap','Nurse','Neurosurgery');
INSERT INTO Empregado VALUES (26,'Kennedy Russell','Clinical assistent','Orthopaedics');
INSERT INTO Empregado VALUES (27,'Gisela Fuentes','Clinical assistent','Psychology');
INSERT INTO Empregado VALUES (28,'Lillian Valdez','Doctor','Gynaecology');
INSERT INTO Empregado VALUES (29,'Rhoda May','Nurse','Proctology');
INSERT INTO Empregado VALUES (30,'Garth Wilder','Doctor','Anesthesiology');
INSERT INTO Empregado VALUES (31,'Ivy Thomas','Doctor','Rheumatology');
INSERT INTO Empregado VALUES (32,'Stephen Baker','Nurse','Endocrinology');
INSERT INTO Empregado VALUES (33,'Devin Campos','Nurse','Urology');
INSERT INTO Empregado VALUES (34,'Wesley Bowman','Nurse','Speech Therapy');
INSERT INTO Empregado VALUES (35,'Vera Wade','Patient services assistent','Nutrition');
INSERT INTO Empregado VALUES (36,'Brendan Stanton','Patient services assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (37,'Rhea Keller','Patient services assistent','Neurosurgery');
INSERT INTO Empregado VALUES (38,'Jesse Patrick','Nurse','Psychology');
INSERT INTO Empregado VALUES (39,'Vanna Wilcox','Patient services assistent','General Medicine');
INSERT INTO Empregado VALUES (40,'Kiayada Mcneil','Clinical assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (41,'Solomon Pearson','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (42,'Christian Shepard','Nurse','Psychiatry');
INSERT INTO Empregado VALUES (43,'Wesley Wynn','Doctor','Endocrinology');
INSERT INTO Empregado VALUES (44,'Porter Spence','Nurse','Proctology');
INSERT INTO Empregado VALUES (45,'Henry Branch','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (46,'Keely Haney','Clinical assistent','Neurosurgery');
INSERT INTO Empregado VALUES (47,'Hakeem Boyer','Patient services assistent','Endocrinology');
INSERT INTO Empregado VALUES (48,'Carolyn Cortez','Patient services assistent','Otolaryngology');
INSERT INTO Empregado VALUES (49,'Daniel England','Patient services assistent','Neuropsychology');
INSERT INTO Empregado VALUES (50,'Brianna Lynch','Clinical assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (51,'Kasper Gallegos','Doctor','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (52,'Geoffrey Erickson','Doctor','Pulmonology');
INSERT INTO Empregado VALUES (53,'Anika Hendricks','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (54,'Raya Knowles','Clinical assistent','Nutrition');
INSERT INTO Empregado VALUES (55,'Nissim Pennington','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (56,'Octavius Gillespie','Clinical assistent','Pulmonology');
INSERT INTO Empregado VALUES (57,'Roanna Conner','Doctor','Rheumatology');
INSERT INTO Empregado VALUES (58,'Colt Mays','Patient services assistent','Anesthesiology');
INSERT INTO Empregado VALUES (59,'Harding Barker','Patient services assistent','Otolaryngology');
INSERT INTO Empregado VALUES (60,'Kristen Medina','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (61,'Gisela Solomon','Patient services assistent','Endocrinology');
INSERT INTO Empregado VALUES (62,'Judah Dale','Nurse','General Practice');
INSERT INTO Empregado VALUES (63,'Timon Mann','Nurse','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (64,'Guy Wolf','Clinical assistent','Gynaecology');
INSERT INTO Empregado VALUES (65,'Malcolm West','Nurse','Neurosurgery');
INSERT INTO Empregado VALUES (66,'Xanthus Singleton','Clinical assistent','Nutrition');
INSERT INTO Empregado VALUES (67,'Sophia Gillespie','Nurse','Gynaecology');
INSERT INTO Empregado VALUES (68,'Chase Cain','Nurse','Nutrition');
INSERT INTO Empregado VALUES (69,'Armando Sosa','Nurse','Nutrition');
INSERT INTO Empregado VALUES (70,'Urielle Drake','Nurse','Proctology');
INSERT INTO Empregado VALUES (71,'Kylee Barron','Doctor','Dermatology');
INSERT INTO Empregado VALUES (72,'Marny Petty','Nurse','Pulmonology');
INSERT INTO Empregado VALUES (73,'Brett Marsh','Clinical assistent','Internal Medicine');
INSERT INTO Empregado VALUES (74,'Karina Mercer','Clinical assistent','Pulmonology');
INSERT INTO Empregado VALUES (75,'Kay Craft','Patient services assistent','Speech Therapy');
INSERT INTO Empregado VALUES (76,'Clayton Bradley','Nurse','Neurology');
INSERT INTO Empregado VALUES (77,'Sarah Bridges','Patient services assistent','General Surgery');
INSERT INTO Empregado VALUES (78,'Gannon Murray','Patient services assistent','General Practice');
INSERT INTO Empregado VALUES (79,'Dieter Franco','Clinical assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (80,'Cody Woods','Doctor','Psychiatry');
INSERT INTO Empregado VALUES (81,'Tad Curry','Patient services assistent','Internal Medicine');
INSERT INTO Empregado VALUES (82,'Phillip Montoya','Doctor','Internal Medicine');
INSERT INTO Empregado VALUES (83,'Cullen Wilder','Doctor','Nutrition');
INSERT INTO Empregado VALUES (84,'Unity Calderon','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (85,'Chanda Bennett','Clinical assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (86,'Kirestin Bonner','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (87,'Mari Guerra','Doctor','Vascular Surgery');
INSERT INTO Empregado VALUES (88,'Charles Hudson','Nurse','Rheumatology');
INSERT INTO Empregado VALUES (89,'Garth Salas','Doctor','Anesthesiology');
INSERT INTO Empregado VALUES (90,'Alec Ingram','Doctor','Proctology');
INSERT INTO Empregado VALUES (91,'Cassidy Dillard','Clinical assistent','General Surgery');
INSERT INTO Empregado VALUES (92,'Dean Ortega','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (93,'Jayme Vinson','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (94,'Murphy Delaney','Doctor','Endocrinology');
INSERT INTO Empregado VALUES (95,'Delilah Mcintosh','Nurse','Nutrition');
INSERT INTO Empregado VALUES (96,'Melanie Wiley','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (97,'Justin Burris','Nurse','Immunohemotherapy');
INSERT INTO Empregado VALUES (98,'Daniel Baird','Nurse','Psychiatry');
INSERT INTO Empregado VALUES (99,'Indigo Mcclure','Nurse','General Surgery');
INSERT INTO Empregado VALUES (100,'Risa Padilla','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (101,'Camilla Terrell','Clinical assistent','General Surgery');
INSERT INTO Empregado VALUES (102,'Aspen Gentry','Nurse','Dermatology');
INSERT INTO Empregado VALUES (103,'Brock Stark','Doctor','Vascular Surgery');
INSERT INTO Empregado VALUES (104,'Zorita Love','Patient services assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (105,'Ira Newman','Patient services assistent','Internal Medicine');
INSERT INTO Empregado VALUES (106,'Troy Witt','Nurse','General Practice');
INSERT INTO Empregado VALUES (107,'Silas Rivas','Doctor','Rheumatology');
INSERT INTO Empregado VALUES (108,'Claudia Hayden','Clinical assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (109,'Rhona Bowen','Patient services assistent','Proctology');
INSERT INTO Empregado VALUES (110,'Anastasia Holmes','Nurse','Psychology');
INSERT INTO Empregado VALUES (111,'Scott Frederick','Doctor','Psychiatry');
INSERT INTO Empregado VALUES (112,'Melvin Parrish','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (113,'Tana Valenzuela','Doctor','Imaging');
INSERT INTO Empregado VALUES (114,'Channing Dickerson','Doctor','Urology');
INSERT INTO Empregado VALUES (115,'Mechelle Caldwell','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (116,'Addison Sanford','Patient services assistent','Anesthesiology');
INSERT INTO Empregado VALUES (117,'Ray Prince','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (118,'Althea Dudley','Clinical assistent','Nefrology');
INSERT INTO Empregado VALUES (119,'Kelly Frost','Nurse','Cardiology');
INSERT INTO Empregado VALUES (120,'Clayton Tanner','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (121,'Simone Walton','Clinical assistent','General Medicine');
INSERT INTO Empregado VALUES (122,'Molly Lowe','Nurse','Internal Medicine');
INSERT INTO Empregado VALUES (123,'Mara Castaneda','Doctor','Immunohemotherapy');
INSERT INTO Empregado VALUES (124,'Rogan Frazier','Nurse','Otolaryngology');
INSERT INTO Empregado VALUES (125,'Galvin Bolton','Patient services assistent','Internal Medicine');
INSERT INTO Empregado VALUES (126,'Teegan Lyons','Patient services assistent','Neurosurgery');
INSERT INTO Empregado VALUES (127,'Seth Torres','Patient services assistent','General Surgery');
INSERT INTO Empregado VALUES (128,'Alan Miles','Patient services assistent','Speech Therapy');
INSERT INTO Empregado VALUES (129,'Galena Alford','Patient services assistent','Urology');
INSERT INTO Empregado VALUES (130,'Velma Savage','Doctor','Gynaecology');
INSERT INTO Empregado VALUES (131,'Jerry Espinoza','Nurse','Dermatology');
INSERT INTO Empregado VALUES (132,'Grace Craft','Nurse','Speech Therapy');
INSERT INTO Empregado VALUES (133,'MacKenzie Hayes','Doctor','General Medicine');
INSERT INTO Empregado VALUES (134,'Duncan Bean','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (135,'Keith Reeves','Doctor','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (136,'Griffith Eaton','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (137,'Keith Barrett','Doctor','Endocrinology');
INSERT INTO Empregado VALUES (138,'Leah Zimmerman','Patient services assistent','Ophthalmology');
INSERT INTO Empregado VALUES (139,'Carlos Young','Nurse','Pulmonology');
INSERT INTO Empregado VALUES (140,'Olga Gilmore','Patient services assistent','Urology');
INSERT INTO Empregado VALUES (141,'Uriah Doyle','Doctor','Proctology');
INSERT INTO Empregado VALUES (142,'Conan Pope','Doctor','Psychology');
INSERT INTO Empregado VALUES (143,'Ora Sandoval','Patient services assistent','Imaging');
INSERT INTO Empregado VALUES (144,'Melanie Morgan','Doctor','Immunohemotherapy');
INSERT INTO Empregado VALUES (145,'Evan Gonzalez','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (146,'Arsenio Mcfarland','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (147,'Faith Fitzgerald','Patient services assistent','Ophthalmology');
INSERT INTO Empregado VALUES (148,'Jeremy Evans','Clinical assistent','Internal Medicine');
INSERT INTO Empregado VALUES (149,'Jin Benson','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (150,'Raya Brock','Nurse','Urology');
INSERT INTO Empregado VALUES (151,'Vernon Campbell','Nurse','Neurosurgery');
INSERT INTO Empregado VALUES (152,'Amber Flowers','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (153,'Shellie Snow','Nurse','Neuropsychology');
INSERT INTO Empregado VALUES (154,'Calista Berger','Patient services assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (155,'Tana Ashley','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (156,'Lana Sawyer','Patient services assistent','Orthopaedics');
INSERT INTO Empregado VALUES (157,'Yolanda Franklin','Clinical assistent','Orthopaedics');
INSERT INTO Empregado VALUES (158,'Rama Harrell','Patient services assistent','Orthopaedics');
INSERT INTO Empregado VALUES (159,'Henry Hayes','Clinical assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (160,'Orlando Bush','Nurse','Cardiology');
INSERT INTO Empregado VALUES (161,'Brent Wilcox','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (162,'Tanek Cotton','Clinical assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (163,'Oren Barnett','Nurse','Otolaryngology');
INSERT INTO Empregado VALUES (164,'Raymond Lowe','Clinical assistent','Rheumatology');
INSERT INTO Empregado VALUES (165,'Leilani Cannon','Patient services assistent','Urology');
INSERT INTO Empregado VALUES (166,'Gay Snider','Nurse','Pulmonology');
INSERT INTO Empregado VALUES (167,'Rachel Stark','Clinical assistent','Gynaecology');
INSERT INTO Empregado VALUES (168,'Jonah Chan','Nurse','Rheumatology');
INSERT INTO Empregado VALUES (169,'Maggie Herring','Patient services assistent','General Surgery');
INSERT INTO Empregado VALUES (170,'Florence Mcneil','Nurse','Psychiatry');
INSERT INTO Empregado VALUES (171,'Jena Hall','Patient services assistent','Psychology');
INSERT INTO Empregado VALUES (172,'Dorian Wright','Nurse','Pulmonology');
INSERT INTO Empregado VALUES (173,'Drew Estrada','Clinical assistent','Nutrition');
INSERT INTO Empregado VALUES (174,'Stacy Montgomery','Patient services assistent','Otolaryngology');
INSERT INTO Empregado VALUES (175,'Kenyon Doyle','Doctor','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (176,'Howard Velez','Patient services assistent','Urology');
INSERT INTO Empregado VALUES (177,'Aladdin Ayala','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (178,'Brooke Berg','Nurse','Nutrition');
INSERT INTO Empregado VALUES (179,'Rhea Mccall','Doctor','Internal Medicine');
INSERT INTO Empregado VALUES (180,'Cullen Gamble','Nurse','Anesthesiology');
INSERT INTO Empregado VALUES (181,'Ashely Bender','Clinical assistent','Otolaryngology');
INSERT INTO Empregado VALUES (182,'Hector Vinson','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (183,'Joshua Kirkland','Doctor','Otolaryngology');
INSERT INTO Empregado VALUES (184,'Zeph Farrell','Patient services assistent','Neurology');
INSERT INTO Empregado VALUES (185,'Hannah Meyer','Clinical assistent','Anesthesiology');
INSERT INTO Empregado VALUES (186,'Hanae Langley','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (187,'Ivory Holland','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (188,'Uriel Woodward','Nurse','Rheumatology');
INSERT INTO Empregado VALUES (189,'Jaquelyn Daniel','Nurse','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (190,'Nayda Bonner','Nurse','Cardiology');
INSERT INTO Empregado VALUES (191,'Petra Sargent','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (192,'Sophia Finch','Doctor','Proctology');
INSERT INTO Empregado VALUES (193,'Sylvester Farmer','Clinical assistent','Psychology');
INSERT INTO Empregado VALUES (194,'Howard Le','Clinical assistent','Nefrology');
INSERT INTO Empregado VALUES (195,'Beatrice Parsons','Patient services assistent','Proctology');
INSERT INTO Empregado VALUES (196,'Kristen Puckett','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (197,'Yetta Decker','Patient services assistent','Neurosurgery');
INSERT INTO Empregado VALUES (198,'Jaquelyn Newton','Nurse','Nefrology');
INSERT INTO Empregado VALUES (199,'Nerea Hendrix','Doctor','Gynaecology');
INSERT INTO Empregado VALUES (200,'Abraham Shepherd','Patient services assistent','Endocrinology');
INSERT INTO Empregado VALUES (201,'Raja Ross','Nurse','Otolaryngology');
INSERT INTO Empregado VALUES (202,'Kirsten Howe','Patient services assistent','General Practice');
INSERT INTO Empregado VALUES (203,'Kyle Lawrence','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (204,'Britanney Cameron','Patient services assistent','Otolaryngology');
INSERT INTO Empregado VALUES (205,'Giselle Montoya','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (206,'Phelan Vance','Doctor','Otolaryngology');
INSERT INTO Empregado VALUES (207,'Zeus Cobb','Patient services assistent','General Practice');
INSERT INTO Empregado VALUES (208,'Emi Burt','Nurse','General Surgery');
INSERT INTO Empregado VALUES (209,'Leah Simmons','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (210,'Kaye Moran','Patient services assistent','General Practice');
INSERT INTO Empregado VALUES (211,'Lacey Benjamin','Patient services assistent','Ophthalmology');
INSERT INTO Empregado VALUES (212,'Fatima Allen','Clinical assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (213,'Noah Caldwell','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (214,'Emmanuel Mcknight','Patient services assistent','Neurology');
INSERT INTO Empregado VALUES (215,'Wynne Schultz','Patient services assistent','Pulmonology');
INSERT INTO Empregado VALUES (216,'Nina Cochran','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (217,'Stewart Silva','Nurse','Neuropsychology');
INSERT INTO Empregado VALUES (218,'Quinlan Bradford','Doctor','Urology');
INSERT INTO Empregado VALUES (219,'Marah Stokes','Patient services assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (220,'Dustin Martinez','Doctor','Gynaecology');
INSERT INTO Empregado VALUES (221,'Castor Swanson','Clinical assistent','Rheumatology');
INSERT INTO Empregado VALUES (222,'Angela Calhoun','Doctor','General Medicine');
INSERT INTO Empregado VALUES (223,'Virginia Chaney','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (224,'Hop Nunez','Doctor','Nefrology');
INSERT INTO Empregado VALUES (225,'Francesca Mccormick','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (226,'Lars Guerra','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (227,'Olympia Fisher','Clinical assistent','Otolaryngology');
INSERT INTO Empregado VALUES (228,'Cooper Hogan','Nurse','Cardiology');
INSERT INTO Empregado VALUES (229,'Dustin Walker','Clinical assistent','Rheumatology');
INSERT INTO Empregado VALUES (230,'Orla Fitzgerald','Nurse','Psychiatry');
INSERT INTO Empregado VALUES (231,'Jackson Bentley','Clinical assistent','Cardiology');
INSERT INTO Empregado VALUES (232,'Tobias Kerr','Nurse','Nefrology');
INSERT INTO Empregado VALUES (233,'Beatrice Cross','Nurse','General Practice');
INSERT INTO Empregado VALUES (234,'Chancellor Camacho','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (235,'Dolan Russell','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (236,'Ethan Hendricks','Patient services assistent','Ophthalmology');
INSERT INTO Empregado VALUES (237,'Colleen Patton','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (238,'Bell Mcmahon','Nurse','Rheumatology');
INSERT INTO Empregado VALUES (239,'Lilah Coleman','Clinical assistent','Psychiatry');
INSERT INTO Empregado VALUES (240,'Yeo Holder','Patient services assistent','Neurosurgery');
INSERT INTO Empregado VALUES (241,'Noelani Willis','Clinical assistent','Nutrition');
INSERT INTO Empregado VALUES (242,'Kyla Colon','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (243,'Jerry Hines','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (244,'Hoyt Glover','Nurse','Speech Therapy');
INSERT INTO Empregado VALUES (245,'Deanna Atkins','Clinical assistent','Nefrology');
INSERT INTO Empregado VALUES (246,'Katelyn Velez','Patient services assistent','General Surgery');
INSERT INTO Empregado VALUES (247,'Linda Richardson','Nurse','Cardiology');
INSERT INTO Empregado VALUES (248,'Norman Stout','Doctor','Internal Medicine');
INSERT INTO Empregado VALUES (249,'Haley Stewart','Clinical assistent','General Practice');
INSERT INTO Empregado VALUES (250,'Helen Macias','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (251,'Debra Woods','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (252,'Donna Cook','Doctor','Neurology');
INSERT INTO Empregado VALUES (253,'Brady Best','Patient services assistent','Anesthesiology');
INSERT INTO Empregado VALUES (254,'Colin Mercer','Clinical assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (255,'Alfonso Schmidt','Doctor','Psychiatry');
INSERT INTO Empregado VALUES (256,'Dana Garza','Patient services assistent','Psychiatry');
INSERT INTO Empregado VALUES (257,'Winifred Dickerson','Nurse','Cardiology');
INSERT INTO Empregado VALUES (258,'Miranda Lopez','Nurse','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (259,'Victor Ashley','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (260,'Deacon Pope','Patient services assistent','Endocrinology');
INSERT INTO Empregado VALUES (261,'Justina Hickman','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (262,'Hamish Kennedy','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (263,'Mikayla Bryant','Patient services assistent','Psychiatry');
INSERT INTO Empregado VALUES (264,'Cade Fernandez','Nurse','Immunohemotherapy');
INSERT INTO Empregado VALUES (265,'Wilma Mason','Patient services assistent','Psychiatry');
INSERT INTO Empregado VALUES (266,'Abdul Contreras','Doctor','Proctology');
INSERT INTO Empregado VALUES (267,'Nell Merrill','Doctor','Ophthalmology');
INSERT INTO Empregado VALUES (268,'Abraham Salinas','Doctor','Immunohemotherapy');
INSERT INTO Empregado VALUES (269,'Michael Kim','Clinical assistent','Psychology');
INSERT INTO Empregado VALUES (270,'Cooper Bullock','Nurse','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (271,'Erich Mcbride','Patient services assistent','General Medicine');
INSERT INTO Empregado VALUES (272,'Upton Guy','Doctor','Proctology');
INSERT INTO Empregado VALUES (273,'Gretchen Austin','Doctor','General Medicine');
INSERT INTO Empregado VALUES (274,'Jada Kennedy','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (275,'Timothy Cole','Patient services assistent','Dermatology');
INSERT INTO Empregado VALUES (276,'Micah Franks','Nurse','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (277,'Lucas Hood','Nurse','Neurology');
INSERT INTO Empregado VALUES (278,'Keelie Harding','Patient services assistent','Urology');
INSERT INTO Empregado VALUES (279,'Colin Mcpherson','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (280,'Ann Tran','Patient services assistent','Internal Medicine');
INSERT INTO Empregado VALUES (281,'Evelyn Villarreal','Doctor','Cardiology');
INSERT INTO Empregado VALUES (282,'Alika Avery','Nurse','Anesthesiology');
INSERT INTO Empregado VALUES (283,'Ciaran Ratliff','Patient services assistent','Gynaecology');
INSERT INTO Empregado VALUES (284,'Whilemina Jennings','Nurse','General Practice');
INSERT INTO Empregado VALUES (285,'Lamar Gardner','Patient services assistent','Neuropsychology');
INSERT INTO Empregado VALUES (286,'Imani James','Doctor','Endocrinology');
INSERT INTO Empregado VALUES (287,'Margaret Macdonald','Clinical assistent','Psychiatry');
INSERT INTO Empregado VALUES (288,'Leilani Graves','Doctor','Nefrology');
INSERT INTO Empregado VALUES (289,'Sierra Cummings','Doctor','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (290,'Grady Russell','Clinical assistent','Psychiatry');
INSERT INTO Empregado VALUES (291,'Hashim Riley','Nurse','Pulmonology');
INSERT INTO Empregado VALUES (292,'Zena Holt','Clinical assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (293,'Clark Rich','Nurse','Imaging');
INSERT INTO Empregado VALUES (294,'Jamalia Mcclain','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (295,'Bryar Cooley','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (296,'Timothy Andrews','Clinical assistent','Dermatology');
INSERT INTO Empregado VALUES (297,'Noel Trujillo','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (298,'Paki Richards','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (299,'Michelle Conrad','Doctor','General Medicine');
INSERT INTO Empregado VALUES (300,'Alea Armstrong','Patient services assistent','Neurology');
INSERT INTO Empregado VALUES (301,'Eaton Grant','Nurse','Anesthesiology');
INSERT INTO Empregado VALUES (302,'Jeanette Skinner','Clinical assistent','Orthopaedics');
INSERT INTO Empregado VALUES (303,'Reuben Dickerson','Nurse','Neurology');
INSERT INTO Empregado VALUES (304,'Imogene Case','Doctor','Anesthesiology');
INSERT INTO Empregado VALUES (305,'Adria Delacruz','Patient services assistent','Speech Therapy');
INSERT INTO Empregado VALUES (306,'Angela Price','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (307,'Blythe Fernandez','Nurse','Cardiology');
INSERT INTO Empregado VALUES (308,'Evangeline Garner','Clinical assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (309,'Kitra Cherry','Nurse','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (310,'Gloria Bernard','Nurse','Cardiology');
INSERT INTO Empregado VALUES (311,'Uriah Benson','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (312,'Ifeoma Sanders','Clinical assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (313,'Salvador Davenport','Clinical assistent','General Surgery');
INSERT INTO Empregado VALUES (314,'Gregory Case','Nurse','Otolaryngology');
INSERT INTO Empregado VALUES (315,'Colin Burton','Doctor','Psychology');
INSERT INTO Empregado VALUES (316,'Graham Molina','Nurse','Nefrology');
INSERT INTO Empregado VALUES (317,'Jillian Carlson','Clinical assistent','Psychology');
INSERT INTO Empregado VALUES (318,'Lacy Taylor','Nurse','Otolaryngology');
INSERT INTO Empregado VALUES (319,'Matthew Greer','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (320,'Hannah Mckee','Doctor','Imaging');
INSERT INTO Empregado VALUES (321,'Yoko Lindsay','Patient services assistent','Neurology');
INSERT INTO Empregado VALUES (322,'Murphy Sanford','Doctor','Psychology');
INSERT INTO Empregado VALUES (323,'Norman Atkinson','Doctor','Neurosurgery');
INSERT INTO Empregado VALUES (324,'Elijah Slater','Nurse','Endocrinology');
INSERT INTO Empregado VALUES (325,'Lamar Baker','Doctor','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (326,'Brett Hood','Nurse','Otolaryngology');
INSERT INTO Empregado VALUES (327,'Oren Cantu','Nurse','Anesthesiology');
INSERT INTO Empregado VALUES (328,'Berk Frederick','Doctor','Internal Medicine');
INSERT INTO Empregado VALUES (329,'Jin Nieves','Clinical assistent','Imaging');
INSERT INTO Empregado VALUES (330,'Igor Hurst','Nurse','Nutrition');
INSERT INTO Empregado VALUES (331,'Hashim Richards','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (332,'Skyler Mcdonald','Nurse','Internal Medicine');
INSERT INTO Empregado VALUES (333,'Jason Martinez','Clinical assistent','Nutrition');
INSERT INTO Empregado VALUES (334,'McKenzie Green','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (335,'Vladimir Weber','Patient services assistent','Psychology');
INSERT INTO Empregado VALUES (336,'Gareth Riley','Doctor','Imaging');
INSERT INTO Empregado VALUES (337,'Laurel Miles','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (338,'Glenna Hughes','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (339,'Medge Solomon','Nurse','Nutrition');
INSERT INTO Empregado VALUES (340,'Melodie Cervantes','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (341,'Heidi Owen','Doctor','Pulmonology');
INSERT INTO Empregado VALUES (342,'Wyoming Holmes','Patient services assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (343,'Jakeem Good','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (344,'Barbara Vega','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (345,'Christen Rosario','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (346,'Katell Sheppard','Patient services assistent','General Practice');
INSERT INTO Empregado VALUES (347,'Hammett Leblanc','Nurse','General Practice');
INSERT INTO Empregado VALUES (348,'Derek Lara','Clinical assistent','Otolaryngology');
INSERT INTO Empregado VALUES (349,'Xander Frederick','Clinical assistent','Pulmonology');
INSERT INTO Empregado VALUES (350,'Glenna Welch','Doctor','Pulmonology');
INSERT INTO Empregado VALUES (351,'Hop Herring','Nurse','Nefrology');
INSERT INTO Empregado VALUES (352,'Carter Bell','Doctor','Dermatology');
INSERT INTO Empregado VALUES (353,'Kaseem Marshall','Clinical assistent','Dermatology');
INSERT INTO Empregado VALUES (354,'Colorado Tillman','Patient services assistent','Speech Therapy');
INSERT INTO Empregado VALUES (355,'Morgan Garner','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (356,'Kim Warren','Doctor','Anesthesiology');
INSERT INTO Empregado VALUES (357,'Danielle Morris','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (358,'Kieran Hanson','Doctor','Dermatology');
INSERT INTO Empregado VALUES (359,'Tanisha Meyers','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (360,'Emi Harmon','Patient services assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (361,'Jade Le','Clinical assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (362,'Jin Haley','Patient services assistent','Ophthalmology');
INSERT INTO Empregado VALUES (363,'Imani Bridges','Doctor','Nutrition');
INSERT INTO Empregado VALUES (364,'Thane Shaffer','Doctor','Neurosurgery');
INSERT INTO Empregado VALUES (365,'Alma Conrad','Nurse','Imaging');
INSERT INTO Empregado VALUES (366,'Nichole Cook','Patient services assistent','Speech Therapy');
INSERT INTO Empregado VALUES (367,'Lionel Melton','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (368,'Conan Frank','Clinical assistent','Psychiatry');
INSERT INTO Empregado VALUES (369,'Ria George','Doctor','Internal Medicine');
INSERT INTO Empregado VALUES (370,'Zena Roy','Nurse','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (371,'Murphy Sutton','Doctor','Neurology');
INSERT INTO Empregado VALUES (372,'Sopoline Cote','Nurse','Dermatology');
INSERT INTO Empregado VALUES (373,'Demetrius Montoya','Nurse','General Medicine');
INSERT INTO Empregado VALUES (374,'Aspen Mooney','Clinical assistent','Psychiatry');
INSERT INTO Empregado VALUES (375,'Lucas Henry','Doctor','Psychology');
INSERT INTO Empregado VALUES (376,'Joseph Wilkins','Patient services assistent','Ophthalmology');
INSERT INTO Empregado VALUES (377,'Moses Frederick','Clinical assistent','Speech Therapy');
INSERT INTO Empregado VALUES (378,'Dennis Hunt','Nurse','Cardiology');
INSERT INTO Empregado VALUES (379,'Carter Gonzales','Doctor','Dermatology');
INSERT INTO Empregado VALUES (380,'Branden Craig','Nurse','Neurosurgery');
INSERT INTO Empregado VALUES (381,'Rhoda Brewer','Clinical assistent','Anesthesiology');
INSERT INTO Empregado VALUES (382,'Edward Barry','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (383,'Caldwell Oneal','Clinical assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (384,'Clayton Bray','Patient services assistent','General Practice');
INSERT INTO Empregado VALUES (385,'Talon Battle','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (386,'Raven Brock','Clinical assistent','Psychiatry');
INSERT INTO Empregado VALUES (387,'Justina Hale','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (388,'Raphael Solomon','Nurse','Rheumatology');
INSERT INTO Empregado VALUES (389,'Carlos Schroeder','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (390,'Harper Foreman','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (391,'Cameron Potter','Nurse','Urology');
INSERT INTO Empregado VALUES (392,'Zeus Kirk','Patient services assistent','General Medicine');
INSERT INTO Empregado VALUES (393,'Chava Powell','Patient services assistent','General Practice');
INSERT INTO Empregado VALUES (394,'Galena Lynch','Nurse','Gynaecology');
INSERT INTO Empregado VALUES (395,'Tanisha Gonzalez','Clinical assistent','General Medicine');
INSERT INTO Empregado VALUES (396,'Paul Jimenez','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (397,'Galvin Stout','Patient services assistent','General Medicine');
INSERT INTO Empregado VALUES (398,'Octavia Rollins','Doctor','Ophthalmology');
INSERT INTO Empregado VALUES (399,'Olivia Chandler','Nurse','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (400,'Ashton Bartlett','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (401,'Quon Hall','Patient services assistent','Neurosurgery');
INSERT INTO Empregado VALUES (402,'Chancellor Moses','Doctor','Gynaecology');
INSERT INTO Empregado VALUES (403,'Guy Oneill','Doctor','Cardiology');
INSERT INTO Empregado VALUES (404,'Lydia Livingston','Nurse','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (405,'Hammett Hewitt','Patient services assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (406,'George Humphrey','Nurse','Neuropsychology');
INSERT INTO Empregado VALUES (407,'Alma Valencia','Doctor','Nutrition');
INSERT INTO Empregado VALUES (408,'Tara Bird','Doctor','Neurosurgery');
INSERT INTO Empregado VALUES (409,'Reagan Mosley','Clinical assistent','Psychiatry');
INSERT INTO Empregado VALUES (410,'Timon Shaw','Doctor','Neurology');
INSERT INTO Empregado VALUES (411,'Sierra Graham','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (412,'Eve Hebert','Nurse','Speech Therapy');
INSERT INTO Empregado VALUES (413,'Grant Reilly','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (414,'Holly Potts','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (415,'Camilla Nixon','Patient services assistent','Psychology');
INSERT INTO Empregado VALUES (416,'Dale Hunt','Clinical assistent','General Medicine');
INSERT INTO Empregado VALUES (417,'Deanna Hensley','Doctor','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (418,'Bevis Martinez','Patient services assistent','Imaging');
INSERT INTO Empregado VALUES (419,'Jasper Beasley','Clinical assistent','Pulmonology');
INSERT INTO Empregado VALUES (420,'Jonas Zimmerman','Clinical assistent','Neurosurgery');
INSERT INTO Empregado VALUES (421,'Byron Benjamin','Nurse','Neurosurgery');
INSERT INTO Empregado VALUES (422,'Caldwell Bernard','Patient services assistent','Speech Therapy');
INSERT INTO Empregado VALUES (423,'Zelenia Keith','Patient services assistent','Orthopaedics');
INSERT INTO Empregado VALUES (424,'Quemby Sellers','Clinical assistent','General Surgery');
INSERT INTO Empregado VALUES (425,'Ethan Mullen','Nurse','Psychology');
INSERT INTO Empregado VALUES (426,'Amena Wall','Patient services assistent','Endocrinology');
INSERT INTO Empregado VALUES (427,'Lillith Hess','Patient services assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (428,'Kirk Lang','Clinical assistent','Psychology');
INSERT INTO Empregado VALUES (429,'Ramona Cunningham','Nurse','General Medicine');
INSERT INTO Empregado VALUES (430,'Blythe Guerra','Doctor','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (431,'Linus Mcmahon','Nurse','Endocrinology');
INSERT INTO Empregado VALUES (432,'Shellie Gross','Patient services assistent','Anesthesiology');
INSERT INTO Empregado VALUES (433,'Beatrice Osborne','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (434,'Aphrodite Hopkins','Nurse','Endocrinology');
INSERT INTO Empregado VALUES (435,'Oprah Randolph','Doctor','Imaging');
INSERT INTO Empregado VALUES (436,'Erasmus Guzman','Patient services assistent','General Practice');
INSERT INTO Empregado VALUES (437,'Bethany Shaffer','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (438,'Amelia Montgomery','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (439,'Brenden Dickson','Clinical assistent','Rheumatology');
INSERT INTO Empregado VALUES (440,'Vladimir Hyde','Doctor','Nutrition');
INSERT INTO Empregado VALUES (441,'Valentine Bender','Doctor','Orthopaedics');
INSERT INTO Empregado VALUES (442,'Phyllis Sanchez','Patient services assistent','Internal Medicine');
INSERT INTO Empregado VALUES (443,'Geraldine Martin','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (444,'September Rivas','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (445,'Kitra Kirby','Clinical assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (446,'Jessica Nash','Nurse','General Medicine');
INSERT INTO Empregado VALUES (447,'Lacey Burt','Nurse','Psychiatry');
INSERT INTO Empregado VALUES (448,'Willa Hunt','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (449,'Dominic Barnett','Patient services assistent','General Surgery');
INSERT INTO Empregado VALUES (450,'Myra Horne','Clinical assistent','Rheumatology');
INSERT INTO Empregado VALUES (451,'Halla Rivas','Nurse','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (452,'Maggy Nguyen','Clinical assistent','Imaging');
INSERT INTO Empregado VALUES (453,'Camilla Mcdonald','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (454,'Jemima Stevens','Patient services assistent','Otolaryngology');
INSERT INTO Empregado VALUES (455,'Chancellor Stein','Nurse','Nutrition');
INSERT INTO Empregado VALUES (456,'Hu Kidd','Nurse','Psychology');
INSERT INTO Empregado VALUES (457,'Craig Le','Doctor','Internal Medicine');
INSERT INTO Empregado VALUES (458,'Karina Johnston','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (459,'Zachery Park','Nurse','Speech Therapy');
INSERT INTO Empregado VALUES (460,'Linda Rogers','Patient services assistent','Anesthesiology');
INSERT INTO Empregado VALUES (461,'Ignatius Britt','Patient services assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (462,'Jessica Dickson','Clinical assistent','Nefrology');
INSERT INTO Empregado VALUES (463,'Daquan Riggs','Nurse','Psychiatry');
INSERT INTO Empregado VALUES (464,'Amos Robles','Nurse','Proctology');
INSERT INTO Empregado VALUES (465,'Channing Madden','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (466,'Laura Vance','Patient services assistent','Gynaecology');
INSERT INTO Empregado VALUES (467,'Rudyard Lancaster','Doctor','Ophthalmology');
INSERT INTO Empregado VALUES (468,'Nehru Cunningham','Nurse','Orthopaedics');
INSERT INTO Empregado VALUES (469,'Dale Romero','Patient services assistent','Ophthalmology');
INSERT INTO Empregado VALUES (470,'Harlan Lowe','Nurse','Urology');
INSERT INTO Empregado VALUES (471,'Otto Cook','Doctor','Psychiatry');
INSERT INTO Empregado VALUES (472,'Katelyn Holder','Clinical assistent','Gynaecology');
INSERT INTO Empregado VALUES (473,'Odessa Rutledge','Clinical assistent','Cardiology');
INSERT INTO Empregado VALUES (474,'Glenna Hawkins','Patient services assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (475,'Rooney Atkins','Doctor','Ophthalmology');
INSERT INTO Empregado VALUES (476,'Jaquelyn Wilkinson','Doctor','General Practice');
INSERT INTO Empregado VALUES (477,'Lysandra Rojas','Patient services assistent','Proctology');
INSERT INTO Empregado VALUES (478,'Ralph Rivers','Clinical assistent','Cardiology');
INSERT INTO Empregado VALUES (479,'Geraldine Hammond','Nurse','Cardiology');
INSERT INTO Empregado VALUES (480,'Kiara Adkins','Patient services assistent','Nutrition');
INSERT INTO Empregado VALUES (481,'Fritz Key','Patient services assistent','General Medicine');
INSERT INTO Empregado VALUES (482,'Willa Ford','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (483,'Maite Winters','Doctor','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (484,'Britanney Christian','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (485,'Gisela Mcfarland','Nurse','Psychiatry');
INSERT INTO Empregado VALUES (486,'Hayden Steele','Clinical assistent','Orthopaedics');
INSERT INTO Empregado VALUES (487,'Ulysses Hinton','Doctor','Psychology');
INSERT INTO Empregado VALUES (488,'Evan Jarvis','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (489,'Dorothy Wheeler','Doctor','Orthopaedics');
INSERT INTO Empregado VALUES (490,'Elton Vaughn','Clinical assistent','Nutrition');
INSERT INTO Empregado VALUES (491,'Lara Stafford','Clinical assistent','Orthopaedics');
INSERT INTO Empregado VALUES (492,'Sawyer Maldonado','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (493,'Stacey Dunlap','Nurse','Nutrition');
INSERT INTO Empregado VALUES (494,'Georgia Joseph','Clinical assistent','Cardiology');
INSERT INTO Empregado VALUES (495,'Winter Gibson','Nurse','Rheumatology');
INSERT INTO Empregado VALUES (496,'Abbot Barron','Doctor','Nutrition');
INSERT INTO Empregado VALUES (497,'Andrew Wiley','Nurse','Internal Medicine');
INSERT INTO Empregado VALUES (498,'Hoyt Mckay','Doctor','Orthopaedics');
INSERT INTO Empregado VALUES (499,'Zephr Elliott','Nurse','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (500,'Tiger Jacobs','Nurse','Neurology');
INSERT INTO Empregado VALUES (501,'Porter Ryan','Doctor','General Practice');
INSERT INTO Empregado VALUES (502,'Rudyard Velez','Nurse','Orthopaedics');
INSERT INTO Empregado VALUES (503,'Graiden Talley','Clinical assistent','Rheumatology');
INSERT INTO Empregado VALUES (504,'Cameron Jimenez','Doctor','Psychiatry');
INSERT INTO Empregado VALUES (505,'Breanna Slater','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (506,'Moana Short','Doctor','Orthopaedics');
INSERT INTO Empregado VALUES (507,'Christian Little','Doctor','Psychology');
INSERT INTO Empregado VALUES (508,'Abel Cunningham','Nurse','Orthopaedics');
INSERT INTO Empregado VALUES (509,'Curran Porter','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (510,'Alana Hensley','Nurse','Nefrology');
INSERT INTO Empregado VALUES (511,'Hammett Duncan','Nurse','Urology');
INSERT INTO Empregado VALUES (512,'Levi Wiggins','Patient services assistent','Psychology');
INSERT INTO Empregado VALUES (513,'Emi Gaines','Doctor','Anesthesiology');
INSERT INTO Empregado VALUES (514,'Wesley Chaney','Doctor','Urology');
INSERT INTO Empregado VALUES (515,'Rashad Dawson','Nurse','Nefrology');
INSERT INTO Empregado VALUES (516,'Murphy Merrill','Nurse','Internal Medicine');
INSERT INTO Empregado VALUES (517,'Hu Mcgowan','Nurse','Rheumatology');
INSERT INTO Empregado VALUES (518,'Regan Long','Patient services assistent','Neurosurgery');
INSERT INTO Empregado VALUES (519,'Aurora Christensen','Nurse','Pulmonology');
INSERT INTO Empregado VALUES (520,'Josephine Norman','Nurse','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (521,'Neville Dale','Clinical assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (522,'Regan Gilmore','Clinical assistent','Imaging');
INSERT INTO Empregado VALUES (523,'Vanna Hill','Patient services assistent','Neurology');
INSERT INTO Empregado VALUES (524,'Serena Cannon','Patient services assistent','Ophthalmology');
INSERT INTO Empregado VALUES (525,'Tamekah Cruz','Nurse','Internal Medicine');
INSERT INTO Empregado VALUES (526,'James Watts','Nurse','Psychology');
INSERT INTO Empregado VALUES (527,'Leilani Porter','Patient services assistent','Orthopaedics');
INSERT INTO Empregado VALUES (528,'Sydnee Tucker','Nurse','Psychiatry');
INSERT INTO Empregado VALUES (529,'Dana Marsh','Doctor','Immunohemotherapy');
INSERT INTO Empregado VALUES (530,'Colorado Conway','Patient services assistent','Cardiology');
INSERT INTO Empregado VALUES (531,'Colby Terrell','Nurse','Internal Medicine');
INSERT INTO Empregado VALUES (532,'Armand House','Nurse','Immunohemotherapy');
INSERT INTO Empregado VALUES (533,'Arthur Mccullough','Clinical assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (534,'Zenia Nelson','Doctor','Anesthesiology');
INSERT INTO Empregado VALUES (535,'Yoshio Welch','Patient services assistent','General Medicine');
INSERT INTO Empregado VALUES (536,'Cole Perry','Nurse','Urology');
INSERT INTO Empregado VALUES (537,'Willa Guthrie','Patient services assistent','Otolaryngology');
INSERT INTO Empregado VALUES (538,'Maggy Benson','Clinical assistent','Otolaryngology');
INSERT INTO Empregado VALUES (539,'Shaine Wall','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (540,'Jaime Park','Nurse','Neuropsychology');
INSERT INTO Empregado VALUES (541,'Guy Moreno','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (542,'Elliott Cochran','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (543,'Cyrus Harrington','Doctor','Nefrology');
INSERT INTO Empregado VALUES (544,'Fletcher Alexander','Patient services assistent','Orthopaedics');
INSERT INTO Empregado VALUES (545,'Carson Norman','Patient services assistent','General Medicine');
INSERT INTO Empregado VALUES (546,'Craig Brock','Patient services assistent','Cardiology');
INSERT INTO Empregado VALUES (547,'Melodie Huber','Doctor','Psychiatry');
INSERT INTO Empregado VALUES (548,'Harper Nunez','Patient services assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (549,'Leslie Brooks','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (550,'Sylvester Irwin','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (551,'Martha Stanley','Clinical assistent','General Surgery');
INSERT INTO Empregado VALUES (552,'Tarik Irwin','Clinical assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (553,'Debra Skinner','Patient services assistent','Psychology');
INSERT INTO Empregado VALUES (554,'Price Wyatt','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (555,'Gray Francis','Patient services assistent','Nefrology');
INSERT INTO Empregado VALUES (556,'Samuel Mathis','Patient services assistent','General Medicine');
INSERT INTO Empregado VALUES (557,'Ciara Sharp','Patient services assistent','Internal Medicine');
INSERT INTO Empregado VALUES (558,'Byron Dillard','Clinical assistent','General Practice');
INSERT INTO Empregado VALUES (559,'Kane Martinez','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (560,'Chase Ball','Clinical assistent','Pulmonology');
INSERT INTO Empregado VALUES (561,'Asher Justice','Patient services assistent','Pulmonology');
INSERT INTO Empregado VALUES (562,'Kyla Bean','Doctor','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (563,'Lance Mckee','Nurse','Rheumatology');
INSERT INTO Empregado VALUES (564,'Paki Cobb','Patient services assistent','Nutrition');
INSERT INTO Empregado VALUES (565,'Lillith Parrish','Nurse','Neurology');
INSERT INTO Empregado VALUES (566,'Carolyn King','Patient services assistent','Endocrinology');
INSERT INTO Empregado VALUES (567,'Ferdinand Delgado','Clinical assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (568,'Jasper Curry','Patient services assistent','Gynaecology');
INSERT INTO Empregado VALUES (569,'Phelan Lucas','Patient services assistent','Neurology');
INSERT INTO Empregado VALUES (570,'Lenore Wallace','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (571,'Melodie Anderson','Clinical assistent','Pulmonology');
INSERT INTO Empregado VALUES (572,'Ulric Chapman','Doctor','Cardiology');
INSERT INTO Empregado VALUES (573,'Sophia Morgan','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (574,'Zeph Miles','Doctor','Neurology');
INSERT INTO Empregado VALUES (575,'Wade Lopez','Clinical assistent','Gynaecology');
INSERT INTO Empregado VALUES (576,'Ronan Barton','Clinical assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (577,'Jin Patton','Doctor','Gynaecology');
INSERT INTO Empregado VALUES (578,'Susan Clark','Nurse','Neurosurgery');
INSERT INTO Empregado VALUES (579,'Darius Ellis','Patient services assistent','Imaging');
INSERT INTO Empregado VALUES (580,'Nigel Short','Clinical assistent','Internal Medicine');
INSERT INTO Empregado VALUES (581,'Samson Simon','Nurse','General Practice');
INSERT INTO Empregado VALUES (582,'Denton Bolton','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (583,'Scarlet Arnold','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (584,'Kyle Howe','Doctor','General Surgery');
INSERT INTO Empregado VALUES (585,'Raja Clemons','Doctor','Immunohemotherapy');
INSERT INTO Empregado VALUES (586,'Raven Reese','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (587,'Alice Grimes','Nurse','General Medicine');
INSERT INTO Empregado VALUES (588,'Evelyn Lowe','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (589,'Kaye Benson','Clinical assistent','Gynaecology');
INSERT INTO Empregado VALUES (590,'Ira Odom','Doctor','Nutrition');
INSERT INTO Empregado VALUES (591,'Vernon Hoover','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (592,'Fay Russo','Patient services assistent','Neuropsychology');
INSERT INTO Empregado VALUES (593,'Jasmine Macias','Nurse','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (594,'Kai Howard','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (595,'Ginger Skinner','Patient services assistent','Proctology');
INSERT INTO Empregado VALUES (596,'Yolanda Blair','Doctor','Psychology');
INSERT INTO Empregado VALUES (597,'Mira Gibson','Nurse','Orthopaedics');
INSERT INTO Empregado VALUES (598,'Thor Hicks','Patient services assistent','Endocrinology');
INSERT INTO Empregado VALUES (599,'Ramona Page','Patient services assistent','General Medicine');
INSERT INTO Empregado VALUES (600,'Dolan Lewis','Doctor','Rheumatology');
INSERT INTO Empregado VALUES (601,'Brenna Webster','Doctor','General Practice');
INSERT INTO Empregado VALUES (602,'Caryn Knox','Nurse','Immunohemotherapy');
INSERT INTO Empregado VALUES (603,'Nomlanga Montoya','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (604,'Tanya Morrison','Clinical assistent','Gynaecology');
INSERT INTO Empregado VALUES (605,'Megan Patrick','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (606,'Erich Gardner','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (607,'Amery Mays','Nurse','Internal Medicine');
INSERT INTO Empregado VALUES (608,'Steven Barry','Nurse','Nutrition');
INSERT INTO Empregado VALUES (609,'Desirae Sharpe','Nurse','Otolaryngology');
INSERT INTO Empregado VALUES (610,'Kennan Harris','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (611,'Tashya Daniel','Patient services assistent','Otolaryngology');
INSERT INTO Empregado VALUES (612,'Roary Mcdonald','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (613,'Carissa Morgan','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (614,'Jemima Ware','Nurse','Pulmonology');
INSERT INTO Empregado VALUES (615,'Genevieve Hurst','Doctor','Otolaryngology');
INSERT INTO Empregado VALUES (616,'Merritt Bray','Nurse','Anesthesiology');
INSERT INTO Empregado VALUES (617,'Quamar Vaughan','Patient services assistent','Speech Therapy');
INSERT INTO Empregado VALUES (618,'Burton Fry','Nurse','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (619,'Caleb Curry','Clinical assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (620,'Malik Bowen','Clinical assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (621,'Caldwell Jimenez','Patient services assistent','Neurosurgery');
INSERT INTO Empregado VALUES (622,'Lynn Walter','Doctor','Imaging');
INSERT INTO Empregado VALUES (623,'Amery Alexander','Doctor','Pulmonology');
INSERT INTO Empregado VALUES (624,'Byron Carter','Doctor','Nutrition');
INSERT INTO Empregado VALUES (625,'Philip Collins','Nurse','Dermatology');
INSERT INTO Empregado VALUES (626,'Hayes Whitehead','Clinical assistent','Psychiatry');
INSERT INTO Empregado VALUES (627,'Cooper Charles','Patient services assistent','Psychology');
INSERT INTO Empregado VALUES (628,'Stewart Norton','Nurse','Gynaecology');
INSERT INTO Empregado VALUES (629,'Mollie Juarez','Doctor','Nutrition');
INSERT INTO Empregado VALUES (630,'Urielle Tillman','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (631,'Raymond Guthrie','Nurse','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (632,'Maggy Mcguire','Clinical assistent','Imaging');
INSERT INTO Empregado VALUES (633,'Nasim Sexton','Clinical assistent','Cardiology');
INSERT INTO Empregado VALUES (634,'Tara Trujillo','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (635,'Cassandra Hudson','Patient services assistent','Proctology');
INSERT INTO Empregado VALUES (636,'Deacon Dalton','Doctor','Internal Medicine');
INSERT INTO Empregado VALUES (637,'Imani Schmidt','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (638,'Rajah Dale','Doctor','Endocrinology');
INSERT INTO Empregado VALUES (639,'Emi Moon','Doctor','General Medicine');
INSERT INTO Empregado VALUES (640,'Risa Donaldson','Clinical assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (641,'Chandler York','Nurse','Otolaryngology');
INSERT INTO Empregado VALUES (642,'Mannix Horne','Doctor','Urology');
INSERT INTO Empregado VALUES (643,'Cassandra Delgado','Patient services assistent','Psychiatry');
INSERT INTO Empregado VALUES (644,'Patience Terry','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (645,'Conan Nolan','Patient services assistent','Dermatology');
INSERT INTO Empregado VALUES (646,'Hoyt Trujillo','Patient services assistent','Pulmonology');
INSERT INTO Empregado VALUES (647,'Maile Juarez','Patient services assistent','Cardiology');
INSERT INTO Empregado VALUES (648,'Ulysses Bell','Doctor','Gynaecology');
INSERT INTO Empregado VALUES (649,'Olivia Sargent','Clinical assistent','Speech Therapy');
INSERT INTO Empregado VALUES (650,'Whitney Baldwin','Doctor','Ophthalmology');
INSERT INTO Empregado VALUES (651,'Alexa Berger','Doctor','Nefrology');
INSERT INTO Empregado VALUES (652,'Berk Cooke','Nurse','Neurosurgery');
INSERT INTO Empregado VALUES (653,'Georgia Frederick','Clinical assistent','Speech Therapy');
INSERT INTO Empregado VALUES (654,'Dara Horne','Patient services assistent','Imaging');
INSERT INTO Empregado VALUES (655,'Portia Oneil','Patient services assistent','Nefrology');
INSERT INTO Empregado VALUES (656,'Xantha Stark','Patient services assistent','General Surgery');
INSERT INTO Empregado VALUES (657,'Amir Rhodes','Nurse','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (658,'Igor Moody','Nurse','Internal Medicine');
INSERT INTO Empregado VALUES (659,'Justina Young','Doctor','Vascular Surgery');
INSERT INTO Empregado VALUES (660,'Silas Carroll','Doctor','Neurology');
INSERT INTO Empregado VALUES (661,'Gail Lowery','Patient services assistent','Psychology');
INSERT INTO Empregado VALUES (662,'Winter Mcleod','Doctor','Ophthalmology');
INSERT INTO Empregado VALUES (663,'Rajah Jackson','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (664,'Leah Evans','Doctor','Pulmonology');
INSERT INTO Empregado VALUES (665,'Lareina Forbes','Patient services assistent','Psychiatry');
INSERT INTO Empregado VALUES (666,'Lacota Wolf','Nurse','Nefrology');
INSERT INTO Empregado VALUES (667,'Wesley Travis','Clinical assistent','Orthopaedics');
INSERT INTO Empregado VALUES (668,'Tara Middleton','Nurse','Psychology');
INSERT INTO Empregado VALUES (669,'Danielle Savage','Clinical assistent','Cardiology');
INSERT INTO Empregado VALUES (670,'Deirdre Bell','Nurse','General Medicine');
INSERT INTO Empregado VALUES (671,'Calista Vang','Nurse','General Surgery');
INSERT INTO Empregado VALUES (672,'Randall Nunez','Doctor','Immunohemotherapy');
INSERT INTO Empregado VALUES (673,'Marvin Solomon','Nurse','General Practice');
INSERT INTO Empregado VALUES (674,'Amos Salinas','Patient services assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (675,'Gemma Colon','Clinical assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (676,'Cruz Bowen','Doctor','Imaging');
INSERT INTO Empregado VALUES (677,'Cherokee Diaz','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (678,'Leslie Welch','Doctor','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (679,'Bree Howe','Clinical assistent','Dermatology');
INSERT INTO Empregado VALUES (680,'Ivy Tate','Nurse','Ophthalmology');
INSERT INTO Empregado VALUES (681,'Kerry Pickett','Patient services assistent','Neurology');
INSERT INTO Empregado VALUES (682,'Marvin Ratliff','Nurse','Rheumatology');
INSERT INTO Empregado VALUES (683,'Hashim Delgado','Patient services assistent','Speech Therapy');
INSERT INTO Empregado VALUES (684,'Athena Turner','Nurse','Nefrology');
INSERT INTO Empregado VALUES (685,'Simon Sherman','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (686,'Brielle Moore','Patient services assistent','Cardiology');
INSERT INTO Empregado VALUES (687,'Clare Reyes','Clinical assistent','Rheumatology');
INSERT INTO Empregado VALUES (688,'Lila Campbell','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (689,'Cassady Winters','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (690,'Maxine Camacho','Patient services assistent','Endocrinology');
INSERT INTO Empregado VALUES (691,'Nathan Snow','Patient services assistent','Nutrition');
INSERT INTO Empregado VALUES (692,'Hakeem Cantu','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (693,'Jescie Green','Nurse','General Surgery');
INSERT INTO Empregado VALUES (694,'Octavius Davidson','Clinical assistent','Otolaryngology');
INSERT INTO Empregado VALUES (695,'Yasir Cooper','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (696,'Melvin Whitney','Doctor','Psychiatry');
INSERT INTO Empregado VALUES (697,'Nash Cain','Patient services assistent','Proctology');
INSERT INTO Empregado VALUES (698,'Jessamine Brooks','Patient services assistent','General Practice');
INSERT INTO Empregado VALUES (699,'Paul Velazquez','Clinical assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (700,'Sigourney Gentry','Clinical assistent','Dermatology');
INSERT INTO Empregado VALUES (701,'Ashton Ramsey','Doctor','Pulmonology');
INSERT INTO Empregado VALUES (702,'Sydney Becker','Doctor','Endocrinology');
INSERT INTO Empregado VALUES (703,'Whilemina Holt','Patient services assistent','Imaging');
INSERT INTO Empregado VALUES (704,'Cyrus Walton','Clinical assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (705,'Austin Holcomb','Clinical assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (706,'Nadine Simpson','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (707,'Timothy Wolf','Doctor','Ophthalmology');
INSERT INTO Empregado VALUES (708,'Audrey Austin','Clinical assistent','Psychology');
INSERT INTO Empregado VALUES (709,'Sheila Morgan','Patient services assistent','Neuropsychology');
INSERT INTO Empregado VALUES (710,'Tanner Young','Clinical assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (711,'Caryn Dunn','Nurse','General Medicine');
INSERT INTO Empregado VALUES (712,'Colton Langley','Nurse','General Medicine');
INSERT INTO Empregado VALUES (713,'Madeson Albert','Nurse','Pulmonology');
INSERT INTO Empregado VALUES (714,'Ishmael Rowland','Nurse','Psychology');
INSERT INTO Empregado VALUES (715,'Stuart Richards','Patient services assistent','Nefrology');
INSERT INTO Empregado VALUES (716,'Kaitlin Montgomery','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (717,'Griffith Brady','Clinical assistent','Otolaryngology');
INSERT INTO Empregado VALUES (718,'Penelope Romero','Patient services assistent','Nutrition');
INSERT INTO Empregado VALUES (719,'Virginia Jensen','Doctor','General Practice');
INSERT INTO Empregado VALUES (720,'Quinn Vasquez','Clinical assistent','Neurosurgery');
INSERT INTO Empregado VALUES (721,'Jakeem Stevenson','Doctor','Endocrinology');
INSERT INTO Empregado VALUES (722,'Sacha Paul','Clinical assistent','Anesthesiology');
INSERT INTO Empregado VALUES (723,'Paloma Vasquez','Patient services assistent','Orthopaedics');
INSERT INTO Empregado VALUES (724,'Adena Williamson','Doctor','Cardiology');
INSERT INTO Empregado VALUES (725,'Florence Patrick','Clinical assistent','General Practice');
INSERT INTO Empregado VALUES (726,'Hammett Lewis','Doctor','Nefrology');
INSERT INTO Empregado VALUES (727,'Noble Goodman','Doctor','Gynaecology');
INSERT INTO Empregado VALUES (728,'Reese Bradley','Clinical assistent','Neurosurgery');
INSERT INTO Empregado VALUES (729,'Destiny Hendricks','Doctor','Gynaecology');
INSERT INTO Empregado VALUES (730,'Boris Reed','Nurse','Psychology');
INSERT INTO Empregado VALUES (731,'Quintessa Chandler','Patient services assistent','Neuropsychology');
INSERT INTO Empregado VALUES (732,'Preston Gutierrez','Patient services assistent','General Surgery');
INSERT INTO Empregado VALUES (733,'Yetta Wiggins','Clinical assistent','Imaging');
INSERT INTO Empregado VALUES (734,'Brandon Gill','Nurse','Nefrology');
INSERT INTO Empregado VALUES (735,'Kylee Alvarado','Clinical assistent','Neurology');
INSERT INTO Empregado VALUES (736,'Lael Wright','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (737,'Lila Massey','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (738,'Ryan Schmidt','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (739,'Victoria Joseph','Patient services assistent','Urology');
INSERT INTO Empregado VALUES (740,'Stephanie Conner','Nurse','Anesthesiology');
INSERT INTO Empregado VALUES (741,'Alexis Griffith','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (742,'Olivia Foreman','Clinical assistent','Pulmonology');
INSERT INTO Empregado VALUES (743,'Ivy Hardy','Clinical assistent','Neurosurgery');
INSERT INTO Empregado VALUES (744,'Ivor Jackson','Doctor','Urology');
INSERT INTO Empregado VALUES (745,'Cassady Swanson','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (746,'Marsden Holloway','Clinical assistent','Nefrology');
INSERT INTO Empregado VALUES (747,'Theodore Elliott','Clinical assistent','Nefrology');
INSERT INTO Empregado VALUES (748,'Ramona Ruiz','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (749,'Lev Brewer','Patient services assistent','Pulmonology');
INSERT INTO Empregado VALUES (750,'Debra Davenport','Nurse','Neurology');
INSERT INTO Empregado VALUES (751,'Craig Mcdowell','Clinical assistent','Neurosurgery');
INSERT INTO Empregado VALUES (752,'Nigel Conley','Doctor','Ophthalmology');
INSERT INTO Empregado VALUES (753,'Drake Serrano','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (754,'Breanna Nicholson','Nurse','Pulmonology');
INSERT INTO Empregado VALUES (755,'Merrill Fowler','Doctor','Otolaryngology');
INSERT INTO Empregado VALUES (756,'Quinn Kirkland','Patient services assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (757,'Raymond Poole','Patient services assistent','Pulmonology');
INSERT INTO Empregado VALUES (758,'Chastity Velasquez','Doctor','Internal Medicine');
INSERT INTO Empregado VALUES (759,'Armando Parker','Doctor','Imaging');
INSERT INTO Empregado VALUES (760,'Clinton Christensen','Clinical assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (761,'Jemima Pace','Nurse','Endocrinology');
INSERT INTO Empregado VALUES (762,'Larissa Richards','Patient services assistent','Ophthalmology');
INSERT INTO Empregado VALUES (763,'Allegra Browning','Patient services assistent','General Medicine');
INSERT INTO Empregado VALUES (764,'Cherokee Mullen','Patient services assistent','Neurosurgery');
INSERT INTO Empregado VALUES (765,'Jermaine Nieves','Patient services assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (766,'Paloma Butler','Nurse','Anesthesiology');
INSERT INTO Empregado VALUES (767,'Phyllis Carrillo','Doctor','Proctology');
INSERT INTO Empregado VALUES (768,'Angela Castillo','Clinical assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (769,'Cedric Bradford','Clinical assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (770,'Xanthus Klein','Patient services assistent','General Surgery');
INSERT INTO Empregado VALUES (771,'Deirdre Parrish','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (772,'Honorato Rivera','Patient services assistent','Imaging');
INSERT INTO Empregado VALUES (773,'Leo Campbell','Clinical assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (774,'Ruth York','Nurse','Urology');
INSERT INTO Empregado VALUES (775,'Chaim Guzman','Doctor','Proctology');
INSERT INTO Empregado VALUES (776,'Cyrus Carr','Patient services assistent','Gynaecology');
INSERT INTO Empregado VALUES (777,'Blake Patterson','Clinical assistent','Imaging');
INSERT INTO Empregado VALUES (778,'Hashim Mann','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (779,'Lara Horne','Doctor','Otolaryngology');
INSERT INTO Empregado VALUES (780,'Kylie Harmon','Doctor','Immunohemotherapy');
INSERT INTO Empregado VALUES (781,'Gray Puckett','Doctor','Nefrology');
INSERT INTO Empregado VALUES (782,'Karly Johns','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (783,'Emerald Gibbs','Doctor','Urology');
INSERT INTO Empregado VALUES (784,'Isaac Berg','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (785,'Arthur Hogan','Patient services assistent','Urology');
INSERT INTO Empregado VALUES (786,'Baker Duke','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (787,'Katelyn Miller','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (788,'Janna Lee','Nurse','Urology');
INSERT INTO Empregado VALUES (789,'Ethan Guy','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (790,'Holmes Best','Patient services assistent','Speech Therapy');
INSERT INTO Empregado VALUES (791,'Cruz Spencer','Doctor','Imaging');
INSERT INTO Empregado VALUES (792,'Marcia Padilla','Doctor','Cardiology');
INSERT INTO Empregado VALUES (793,'Hilary Wood','Patient services assistent','Internal Medicine');
INSERT INTO Empregado VALUES (794,'Barbara Fleming','Doctor','General Medicine');
INSERT INTO Empregado VALUES (795,'Debra Dorsey','Doctor','Orthopaedics');
INSERT INTO Empregado VALUES (796,'Imani Anthony','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (797,'Maxwell Rocha','Clinical assistent','Urology');
INSERT INTO Empregado VALUES (798,'Ayanna Mclaughlin','Doctor','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (799,'Rinah Leon','Doctor','Proctology');
INSERT INTO Empregado VALUES (800,'Drew Nixon','Doctor','Immunohemotherapy');
INSERT INTO Empregado VALUES (801,'Morgan Bender','Clinical assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (802,'Dylan Curry','Doctor','Proctology');
INSERT INTO Empregado VALUES (803,'Davis Woodward','Nurse','Proctology');
INSERT INTO Empregado VALUES (804,'Shelly Schultz','Nurse','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (805,'Reed Sanchez','Doctor','Nutrition');
INSERT INTO Empregado VALUES (806,'Ahmed Park','Patient services assistent','Dermatology');
INSERT INTO Empregado VALUES (807,'Katelyn Hudson','Doctor','Dermatology');
INSERT INTO Empregado VALUES (808,'Quinlan Mason','Clinical assistent','General Medicine');
INSERT INTO Empregado VALUES (809,'Nichole Stokes','Doctor','General Practice');
INSERT INTO Empregado VALUES (810,'Philip Hardin','Doctor','Psychiatry');
INSERT INTO Empregado VALUES (811,'Octavius Huff','Doctor','Anesthesiology');
INSERT INTO Empregado VALUES (812,'Pascale Ingram','Patient services assistent','Proctology');
INSERT INTO Empregado VALUES (813,'Velma Mitchell','Nurse','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (814,'Shaeleigh Fletcher','Doctor','Gynaecology');
INSERT INTO Empregado VALUES (815,'Cairo Warren','Clinical assistent','Orthopaedics');
INSERT INTO Empregado VALUES (816,'Norman Cotton','Doctor','Immunohemotherapy');
INSERT INTO Empregado VALUES (817,'Aspen Pennington','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (818,'Donovan Harvey','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (819,'Paul Irwin','Patient services assistent','Cardiology');
INSERT INTO Empregado VALUES (820,'Graiden Velasquez','Nurse','Internal Medicine');
INSERT INTO Empregado VALUES (821,'Mona Contreras','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (822,'Alyssa Murphy','Doctor','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (823,'Clementine Vang','Patient services assistent','Psychiatry');
INSERT INTO Empregado VALUES (824,'Justine Burke','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (825,'Judith Kim','Nurse','Dermatology');
INSERT INTO Empregado VALUES (826,'Sacha Velazquez','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (827,'Pandora Franks','Clinical assistent','Psychiatry');
INSERT INTO Empregado VALUES (828,'Chastity Eaton','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (829,'Alec Hebert','Patient services assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (830,'Joel Ortega','Clinical assistent','Dermatology');
INSERT INTO Empregado VALUES (831,'Cherokee Nielsen','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (832,'Zeus Le','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (833,'Boris Coleman','Patient services assistent','Imaging');
INSERT INTO Empregado VALUES (834,'Griffin Bartlett','Clinical assistent','Ophthalmology');
INSERT INTO Empregado VALUES (835,'Drake Burgess','Nurse','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (836,'Merritt Rosario','Doctor','Gynaecology');
INSERT INTO Empregado VALUES (837,'Urielle Klein','Doctor','Otolaryngology');
INSERT INTO Empregado VALUES (838,'Alfreda Workman','Doctor','Vascular Surgery');
INSERT INTO Empregado VALUES (839,'Armando Hill','Doctor','Pulmonology');
INSERT INTO Empregado VALUES (840,'Jennifer Mclaughlin','Clinical assistent','Neuropsychology');
INSERT INTO Empregado VALUES (841,'Garth Ratliff','Nurse','General Practice');
INSERT INTO Empregado VALUES (842,'Vladimir Fuller','Doctor','Imaging');
INSERT INTO Empregado VALUES (843,'Kathleen Flores','Clinical assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (844,'Kermit York','Clinical assistent','Internal Medicine');
INSERT INTO Empregado VALUES (845,'Molly Emerson','Patient services assistent','General Practice');
INSERT INTO Empregado VALUES (846,'Whilemina Conley','Clinical assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (847,'Wendy Woodard','Patient services assistent','Urology');
INSERT INTO Empregado VALUES (848,'Camden Sosa','Doctor','Otolaryngology');
INSERT INTO Empregado VALUES (849,'Whilemina Wilkins','Nurse','Ophthalmology');
INSERT INTO Empregado VALUES (850,'Ishmael Talley','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (851,'Brian Merrill','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (852,'Knox Young','Clinical assistent','Rheumatology');
INSERT INTO Empregado VALUES (853,'Cassady Mclaughlin','Doctor','General Surgery');
INSERT INTO Empregado VALUES (854,'Rhoda Mccarthy','Nurse','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (855,'Sharon Lawrence','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (856,'Eaton Ayers','Patient services assistent','Internal Medicine');
INSERT INTO Empregado VALUES (857,'Magee Wagner','Nurse','Orthopaedics');
INSERT INTO Empregado VALUES (858,'Bernard Hensley','Clinical assistent','Cardiology');
INSERT INTO Empregado VALUES (859,'Carissa Livingston','Nurse','Endocrinology');
INSERT INTO Empregado VALUES (860,'Craig Dejesus','Doctor','General Medicine');
INSERT INTO Empregado VALUES (861,'Carol Branch','Doctor','Rheumatology');
INSERT INTO Empregado VALUES (862,'Erasmus Stanley','Nurse','Psychiatry');
INSERT INTO Empregado VALUES (863,'Brianna Dudley','Doctor','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (864,'Victoria Ferguson','Doctor','Anesthesiology');
INSERT INTO Empregado VALUES (865,'Lesley Blanchard','Patient services assistent','Internal Medicine');
INSERT INTO Empregado VALUES (866,'Lacota Ross','Clinical assistent','Nefrology');
INSERT INTO Empregado VALUES (867,'Malcolm Allison','Patient services assistent','Immunohemotherapy');
INSERT INTO Empregado VALUES (868,'Yen Pittman','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (869,'Damian Mcconnell','Doctor','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (870,'Erin Contreras','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (871,'Lunea Munoz','Doctor','Otolaryngology');
INSERT INTO Empregado VALUES (872,'Walter Beck','Doctor','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (873,'Desirae Trujillo','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (874,'McKenzie Cherry','Doctor','Otolaryngology');
INSERT INTO Empregado VALUES (875,'Cody Hughes','Clinical assistent','Gynaecology');
INSERT INTO Empregado VALUES (876,'Amelia Love','Nurse','General Medicine');
INSERT INTO Empregado VALUES (877,'Vivian Colon','Patient services assistent','Psychiatry');
INSERT INTO Empregado VALUES (878,'Isaac Leach','Doctor','General Surgery');
INSERT INTO Empregado VALUES (879,'Yoko Hart','Doctor','Proctology');
INSERT INTO Empregado VALUES (880,'Otto Anthony','Doctor','Pulmonology');
INSERT INTO Empregado VALUES (881,'Ralph Frank','Clinical assistent','Cardiology');
INSERT INTO Empregado VALUES (882,'Alexander Cabrera','Nurse','Cardiology');
INSERT INTO Empregado VALUES (883,'Katell Oneill','Clinical assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (884,'Berk Beasley','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (885,'Keegan Cantu','Nurse','Psychology');
INSERT INTO Empregado VALUES (886,'Carter Maynard','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (887,'Rylee Mcclure','Nurse','Anesthesiology');
INSERT INTO Empregado VALUES (888,'Lucian Palmer','Patient services assistent','Urology');
INSERT INTO Empregado VALUES (889,'Uta Mendoza','Patient services assistent','Internal Medicine');
INSERT INTO Empregado VALUES (890,'Xantha Gray','Patient services assistent','Endocrinology');
INSERT INTO Empregado VALUES (891,'Katell Lancaster','Patient services assistent','Neuropsychology');
INSERT INTO Empregado VALUES (892,'Rhonda Holman','Doctor','Rheumatology');
INSERT INTO Empregado VALUES (893,'Deacon Osborne','Nurse','Urology');
INSERT INTO Empregado VALUES (894,'Dale Marshall','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (895,'Illana Faulkner','Patient services assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (896,'Aristotle Gutierrez','Doctor','Pulmonology');
INSERT INTO Empregado VALUES (897,'Barclay Hill','Clinical assistent','General Practice');
INSERT INTO Empregado VALUES (898,'Hall Kirkland','Doctor','Psychology');
INSERT INTO Empregado VALUES (899,'Ian Reed','Patient services assistent','Neurology');
INSERT INTO Empregado VALUES (900,'Quamar Dale','Doctor','Dermatology');
INSERT INTO Empregado VALUES (901,'Cassidy Bridges','Nurse','Anesthesiology');
INSERT INTO Empregado VALUES (902,'Reece Petty','Clinical assistent','Cardiology');
INSERT INTO Empregado VALUES (903,'Donna Fitzpatrick','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (904,'Xander Cooke','Clinical assistent','Internal Medicine');
INSERT INTO Empregado VALUES (905,'Mira Wynn','Nurse','Urology');
INSERT INTO Empregado VALUES (906,'Aiko Carroll','Doctor','Imaging');
INSERT INTO Empregado VALUES (907,'Kirsten Stewart','Patient services assistent','Psychology');
INSERT INTO Empregado VALUES (908,'Hope Baxter','Patient services assistent','Psychiatry');
INSERT INTO Empregado VALUES (909,'Quemby Orr','Patient services assistent','Otolaryngology');
INSERT INTO Empregado VALUES (910,'Barbara Carver','Patient services assistent','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (911,'Keane Henderson','Patient services assistent','Gynaecology');
INSERT INTO Empregado VALUES (912,'Malik Levine','Doctor','Nefrology');
INSERT INTO Empregado VALUES (913,'Chase Silva','Clinical assistent','Dermatology');
INSERT INTO Empregado VALUES (914,'Alden Galloway','Patient services assistent','Orthopaedics');
INSERT INTO Empregado VALUES (915,'Hedy Beasley','Patient services assistent','Rheumatology');
INSERT INTO Empregado VALUES (916,'Rhiannon Schmidt','Clinical assistent','General Surgery');
INSERT INTO Empregado VALUES (917,'Kaye Pearson','Doctor','Psychology');
INSERT INTO Empregado VALUES (918,'Kevin Ramos','Doctor','Orthopaedics');
INSERT INTO Empregado VALUES (919,'Kasper Juarez','Nurse','Internal Medicine');
INSERT INTO Empregado VALUES (920,'Meredith Chavez','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (921,'Hannah Marquez','Nurse','Nutrition');
INSERT INTO Empregado VALUES (922,'Sade Anderson','Clinical assistent','Endocrinology');
INSERT INTO Empregado VALUES (923,'Laith Sandoval','Patient services assistent','Vascular Surgery');
INSERT INTO Empregado VALUES (924,'Mufutau Leblanc','Clinical assistent','Anesthesiology');
INSERT INTO Empregado VALUES (925,'Mercedes Underwood','Doctor','Otolaryngology');
INSERT INTO Empregado VALUES (926,'Orla Hodge','Patient services assistent','Nutrition');
INSERT INTO Empregado VALUES (927,'Wynter Chavez','Patient services assistent','General Practice');
INSERT INTO Empregado VALUES (928,'Mollie Compton','Doctor','Speech Therapy');
INSERT INTO Empregado VALUES (929,'Uriah Hoover','Patient services assistent','Dermatology');
INSERT INTO Empregado VALUES (930,'Kylee Brady','Doctor','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (931,'Riley Vega','Nurse','Imaging');
INSERT INTO Empregado VALUES (932,'Zena Olsen','Doctor','General Surgery');
INSERT INTO Empregado VALUES (933,'Gary Franks','Doctor','Neurosurgery');
INSERT INTO Empregado VALUES (934,'Darryl Eaton','Clinical assistent','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (935,'James Holmes','Patient services assistent','Neurosurgery');
INSERT INTO Empregado VALUES (936,'Debra Lyons','Nurse','Neurosurgery');
INSERT INTO Empregado VALUES (937,'Dahlia Mooney','Clinical assistent','Orthopaedics');
INSERT INTO Empregado VALUES (938,'Avram Bush','Clinical assistent','Otolaryngology');
INSERT INTO Empregado VALUES (939,'Emmanuel Schneider','Nurse','Cardiology');
INSERT INTO Empregado VALUES (940,'Clinton Russo','Nurse','Physical and Rehabilitation Medicine');
INSERT INTO Empregado VALUES (941,'Rosalyn Kaufman','Nurse','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (942,'Orson Pacheco','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (943,'Lyle Barber','Nurse','Endocrinology');
INSERT INTO Empregado VALUES (944,'Jorden Luna','Clinical assistent','Psychiatry');
INSERT INTO Empregado VALUES (945,'Alexis Rodriguez','Clinical assistent','Imaging');
INSERT INTO Empregado VALUES (946,'Kevyn Gregory','Nurse','Otolaryngology');
INSERT INTO Empregado VALUES (947,'Victor Buckner','Doctor','Nefrology');
INSERT INTO Empregado VALUES (948,'Nola Strong','Clinical assistent','Orthopaedics');
INSERT INTO Empregado VALUES (949,'Hector Colon','Clinical assistent','Anesthesiology');
INSERT INTO Empregado VALUES (950,'Summer Jacobs','Nurse','Neurosurgery');
INSERT INTO Empregado VALUES (951,'Abigail Stephenson','Doctor','Neuropsychology');
INSERT INTO Empregado VALUES (952,'Rigel Oneill','Doctor','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (953,'Medge Hebert','Clinical assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (954,'Harper Wong','Clinical assistent','Gynaecology');
INSERT INTO Empregado VALUES (955,'Amelia Vasquez','Nurse','Imaging');
INSERT INTO Empregado VALUES (956,'Porter Herrera','Patient services assistent','Neuropsychology');
INSERT INTO Empregado VALUES (957,'Wayne Pacheco','Patient services assistent','Otolaryngology');
INSERT INTO Empregado VALUES (958,'Alexander Jackson','Nurse','Speech Therapy');
INSERT INTO Empregado VALUES (959,'Gannon Glass','Nurse','Rheumatology');
INSERT INTO Empregado VALUES (960,'Wade Byers','Clinical assistent','Speech Therapy');
INSERT INTO Empregado VALUES (961,'Trevor Garza','Clinical assistent','Nefrology');
INSERT INTO Empregado VALUES (962,'Pandora Gillespie','Nurse','Nefrology');
INSERT INTO Empregado VALUES (963,'Fay Nieves','Doctor','Immunohemotherapy');
INSERT INTO Empregado VALUES (964,'Sylvester Stout','Nurse','Vascular Surgery');
INSERT INTO Empregado VALUES (965,'Chantale Horton','Doctor','Rheumatology');
INSERT INTO Empregado VALUES (966,'Cain Kidd','Doctor','Proctology');
INSERT INTO Empregado VALUES (967,'Berk Torres','Clinical assistent','Speech Therapy');
INSERT INTO Empregado VALUES (968,'Molly Kane','Doctor','Anesthesiology');
INSERT INTO Empregado VALUES (969,'Fritz Morton','Doctor','Nutrition');
INSERT INTO Empregado VALUES (970,'Chandler Harding','Clinical assistent','Psychiatry');
INSERT INTO Empregado VALUES (971,'Chadwick Valentine','Clinical assistent','Cardiology');
INSERT INTO Empregado VALUES (972,'Shaeleigh Barrett','Nurse','Immunohemotherapy');
INSERT INTO Empregado VALUES (973,'Isaiah Steele','Clinical assistent','Plastic and Reconstructive Surgery');
INSERT INTO Empregado VALUES (974,'Kyra Mueller','Doctor','General Practice');
INSERT INTO Empregado VALUES (975,'Prescott Mathews','Clinical assistent','Nefrology');
INSERT INTO Empregado VALUES (976,'Lynn Slater','Clinical assistent','Nefrology');
INSERT INTO Empregado VALUES (977,'Keith Compton','Nurse','Imaging');
INSERT INTO Empregado VALUES (978,'Rosalyn Moreno','Patient services assistent','Urology');
INSERT INTO Empregado VALUES (979,'Rajah Houston','Doctor','Dermatology');
INSERT INTO Empregado VALUES (980,'Thaddeus Walter','Clinical assistent','Speech Therapy');
INSERT INTO Empregado VALUES (981,'Dieter Wright','Nurse','Pulmonology');
INSERT INTO Empregado VALUES (982,'Ursa Yang','Clinical assistent','Pulmonology');
INSERT INTO Empregado VALUES (983,'Marny White','Doctor','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (984,'Aurelia Patterson','Doctor','Rheumatology');
INSERT INTO Empregado VALUES (985,'Nissim Hardy','Patient services assistent','Pulmonology');
INSERT INTO Empregado VALUES (986,'Quinlan Blake','Nurse','Urology');
INSERT INTO Empregado VALUES (987,'Dennis Mcneil','Nurse','Gynaecology');
INSERT INTO Empregado VALUES (988,'Amir Boyle','Nurse','General Practice');
INSERT INTO Empregado VALUES (989,'Cheryl Richmond','Patient services assistent','Cardiology');
INSERT INTO Empregado VALUES (990,'Cecilia Mason','Clinical assistent','Pulmonology');
INSERT INTO Empregado VALUES (991,'Dante Black','Doctor','Nutrition');
INSERT INTO Empregado VALUES (992,'Linda Lloyd','Patient services assistent','Neurology');
INSERT INTO Empregado VALUES (993,'Erasmus Vazquez','Nurse','Maxillofacial Surgery');
INSERT INTO Empregado VALUES (994,'Jemima Cobb','Nurse','General Medicine');
INSERT INTO Empregado VALUES (995,'Whilemina Gordon','Clinical assistent','Proctology');
INSERT INTO Empregado VALUES (996,'Leslie May','Patient services assistent','Speech Therapy');
INSERT INTO Empregado VALUES (997,'Mason Gibbs','Clinical assistent','Pulmonology');
INSERT INTO Empregado VALUES (998,'Stone Horn','Patient services assistent','Neurology');
INSERT INTO Empregado VALUES (999,'Dillon Conley','Patient services assistent','Urology');
INSERT INTO Empregado VALUES (1000,'Yael Forbes','Nurse','Gynaecology');

-- and then:

UPDATE Empregado
SET area_especializacao = NULL
WHERE titulo <> 'Doctor'

-- to remove specialty area on everyone who isn't a doctor

UPDATE Empregado
SET titulo = 'Clinical assistant'
WHERE titulo = 'Clinical assistent'

UPDATE Empregado
SET titulo = 'Patient services assistant'
WHERE titulo = 'Patient services assistent'

-- fix typos
